Repository kubernetes/kube-state-metrics, pull requests merged in 2018-03, with the labels that each got.

#379 add secret and configmap metrics
  Documentation/README.md
  Documentation/configmap-metrics.md
  Documentation/secret-metrics.md
  collectors/configmap.go
  collectors/configmap_test.go
  collectors/secret.go
  collectors/secret_test.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#380 update go version to 1.10
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#382 Add kube_daemonset_labels
  Documentation/daemonset-metrics.md
  collectors/daemonset.go
  collectors/daemonset_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#365 Support deployment MaxSurge
  Documentation/deployment-metrics.md
  collectors/deployment.go
  collectors/deployment_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#383 Add annotations to namespace collector
  Documentation/namespace-metrics.md
  collectors/namespace.go
  collectors/namespace_test.go
  collectors/pod.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#385 Add _labels for pv and pvc.
  Documentation/persistentvolume-metrics.md
  Documentation/persistentvolumeclaim-metrics.md
  collectors/persistentvolume.go
  collectors/persistentvolume_test.go
  collectors/persistentvolumeclaim.go
  collectors/persistentvolumeclaim_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#389 Add Pod persistentvolumeclaim binding information.
  Documentation/pod-metrics.md
  collectors/pod.go
  collectors/pod_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#390 fix cronjob parse
  collectors/cronjob.go
  collectors/cronjob_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#387 Remove namespace from PersistentVolume metrics
  collectors/persistentvolume.go
  collectors/persistentvolume_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#392 fix misspelling of Kubernetes
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#394 Fix namespacing of HPA
  collectors/hpa.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#396 collectors: Report pod's completion time
  CHANGELOG.md
  Documentation/pod-metrics.md
  collectors/pod.go
  collectors/pod_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#397 Add Unreleased section in CHANGELOG
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#395 [RFC] Allow to specify multiple namespace.
  collectors/collectors.go
  collectors/configmap.go
  collectors/cronjob.go
  collectors/daemonset.go
  collectors/deployment.go
  collectors/endpoint.go
  collectors/hpa.go
  collectors/job.go
  collectors/limitrange.go
  collectors/namespace.go
  collectors/node.go
  collectors/persistentvolume.go
  collectors/persistentvolumeclaim.go
  collectors/pod.go
  collectors/replicaset.go
  collectors/replicationcontroller.go
  collectors/resourcequota.go
  collectors/secret.go
  collectors/service.go
  collectors/statefulset.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#386 update namespace doc
  Documentation/namespace-metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#391 Add metrics for node taints
  Documentation/node-metrics.md
  collectors/node.go
  collectors/node_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#400 Updated CHANGELOG
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#399 sanity check
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#406 fix cronjob parse
  collectors/cronjob.go
  collectors/cronjob_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#404 CHANGELOG.md: Add v1.3.0-rc.0 entry
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/S
