Repository kubernetes/kube-state-metrics, pull requests merged in 2018-04, with the labels that each got.

#411 update readme for cronjob collector
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#413 Add permissions to list and watch ConfigMaps and Secrets
  kubernetes/kube-state-metrics-cluster-role.yaml
Labels: cncf-cla: yes, size/XS

#412 Cut v1.3.0 stable
  CHANGELOG.md
  README.md
  kubernetes/kube-state-metrics-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#420 fix pod unknown stats
  Godeps/Godeps.json
  collectors/pod.go
  collectors/pod_test.go
  vendor/golang.org/x/text/internal/gen.go
  vendor/golang.org/x/text/internal/internal.go
  vendor/golang.org/x/text/internal/match.go
  vendor/golang.org/x/text/internal/tables.go
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/BUILD
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/errors.go
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/util.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/BUILD
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/BUILD
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/OWNERS
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/fields.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/doc.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/document.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/openapi.go
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/pkg/apis/core/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/core/OWNERS
  vendor/k8s.io/kubernetes/pkg/apis/core/annotation_key_constants.go
  vendor/k8s.io/kubernetes/pkg/apis/core/doc.go
  vendor/k8s.io/kubernetes/pkg/apis/core/field_constants.go
  vendor/k8s.io/kubernetes/pkg/apis/core/json.go
  vendor/k8s.io/kubernetes/pkg/apis/core/objectreference.go
  vendor/k8s.io/kubernetes/pkg/apis/core/register.go
  vendor/k8s.io/kubernetes/pkg/apis/core/resource.go
  vendor/k8s.io/kubernetes/pkg/apis/core/taint.go
  vendor/k8s.io/kubernetes/pkg/apis/core/toleration.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/well_known_annotations.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/well_known_labels.go
  vendor/k8s.io/kubernetes/pkg/util/node/BUILD
  vendor/k8s.io/kubernetes/pkg/util/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#419 use alpine as base image
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#424 pin minikube v0.25.2
  scripts/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#422 use golang image to compile ksm
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#423 Add note about kube-state-metrics exposing raw data
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#429 Cut 1.3.1
  .travis.yml
  CHANGELOG.md
  Godeps/Godeps.json
  Makefile
  collectors/pod.go
  collectors/pod_test.go
  scripts/e2e.sh
  vendor/golang.org/x/text/internal/gen.go
  vendor/golang.org/x/text/internal/internal.go
  vendor/golang.org/x/text/internal/match.go
  vendor/golang.org/x/text/internal/tables.go
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/BUILD
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/errors.go
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/util.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/BUILD
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/BUILD
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/OWNERS
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/fields.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/doc.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/document.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/openapi.go
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/pkg/apis/core/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/core/OWNERS
  vendor/k8s.io/kubernetes/pkg/apis/core/annotation_key_constants.go
  vendor/k8s.io/kubernetes/pkg/apis/core/doc.go
  vendor/k8s.io/kubernetes/pkg/apis/core/field_constants.go
  vendor/k8s.io/kubernetes/pkg/apis/core/json.go
  vendor/k8s.io/kubernetes/pkg/apis/core/objectreference.go
  vendor/k8s.io/kubernetes/pkg/apis/core/register.go
  vendor/k8s.io/kubernetes/pkg/apis/core/resource.go
  vendor/k8s.io/kubernetes/pkg/apis/core/taint.go
  vendor/k8s.io/kubernetes/pkg/apis/core/toleration.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/well_known_annotations.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/well_known_labels.go
  vendor/k8s.io/kubernetes/pkg/util/node/BUILD
  vendor/k8s.io/kubernetes/pkg/util/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#432 Clarify apiserver override example.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#434 Fix documentation typo 'Heaspter' -> 'Heapster'
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#418 Extend e2e tests
  Documentation/job-metrics.md
  Makefile
  collectors/job.go
  collectors/job_test.go
  tests/README.md
  tests/e2e.sh
  tests/manifests/cronjob.yaml
  tests/manifests/daemonset.yaml
  tests/manifests/hpa.yaml
  tests/manifests/job.yaml
  tests/manifests/limitrange.yaml
  tests/manifests/persistentvolume.yaml
  tests/manifests/persistentvolumeclaim.yaml
  tests/manifests/replicationcontroller.yaml
  tests/manifests/resourcequota.yaml
  tests/manifests/statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#437 Updated changelog according to changes in #418
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#439 Fix markdown rendering of possible reason tag values
  Documentation/pod-metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#436 Add hpa conditions
  collectors/collectors.go
  collectors/hpa.go
  collectors/hpa_test.go
  collectors/node.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#433 Adds time_to_schedule and time_to_start metrics
  Documentation/pod-metrics.md
  collectors/pod.go
  collectors/pod_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#441 Fix hpa condition labels
  collectors/hpa.go
Labels: cncf-cla: yes, size/XS

#444 Update README.md to reference 1.3.1 as latest release
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#445 add support for quay latest image tag
  Makefile
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#447 add ISSUE and pr guildline
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/M
