Repository kubernetes/kube-state-metrics, pull requests merged in 2018-06, with the labels that each got.

#466 add generic node resource capacity and allocatable
  Documentation/node-metrics.md
  README.md
  pkg/collectors/node.go
  pkg/collectors/node_test.go
  pkg/collectors/pod.go
  pkg/constant/resource_unit.go
  pkg/options/options.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#473 using defined variables instead of magic strings
  .travis.yml
  pkg/collectors/configmap.go
  pkg/collectors/cronjob.go
  pkg/collectors/daemonset.go
  pkg/collectors/deployment.go
  pkg/collectors/endpoint.go
  pkg/collectors/hpa.go
  pkg/collectors/job.go
  pkg/collectors/limitrange.go
  pkg/collectors/namespace.go
  pkg/collectors/node.go
  pkg/collectors/persistentvolume.go
  pkg/collectors/persistentvolumeclaim.go
  pkg/collectors/pod.go
  pkg/collectors/replicaset.go
  pkg/collectors/replicationcontroller.go
  pkg/collectors/resourcequota.go
  pkg/collectors/secret.go
  pkg/collectors/service.go
  pkg/collectors/statefulset.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#477 add current status for each metrics
  Documentation/README.md
  Documentation/configmap-metrics.md
  Documentation/cronjob-metrics.md
  Documentation/daemonset-metrics.md
  Documentation/deployment-metrics.md
  Documentation/endpoint-metrics.md
  Documentation/horizontalpodautoscaler-metrics.md
  Documentation/job-metrics.md
  Documentation/limitrange-metrics.md
  Documentation/namespace-metrics.md
  Documentation/node-metrics.md
  Documentation/persistentvolume-metrics.md
  Documentation/persistentvolumeclaim-metrics.md
  Documentation/pod-metrics.md
  Documentation/replicaset-metrics.md
  Documentation/replicationcontroller-metrics.md
  Documentation/resourcequota-metrics.md
  Documentation/secret-metrics.md
  Documentation/service-metrics.md
  Documentation/statefulset-metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#476 avoid dirty hack to prometheus client
  Godeps/Godeps.json
  pkg/collectors/pod_test.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/doc.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/http.go
  vendor/github.com/prometheus/client_golang/prometheus/labels.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/observer.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_pre_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/timer.go
  vendor/github.com/prometheus/client_golang/prometheus/untyped.go
  vendor/github.com/prometheus/client_golang/prometheus/value.go
  vendor/github.com/prometheus/client_golang/prometheus/vec.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#479 Information sinking
  Documentation/README.md
  Makefile
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#475 prefer protobuf instead of just json format
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#482 adjust client-go User-Agent
  main.go
  pkg/version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
