Repository kubernetes/kube-state-metrics, pull requests merged in 2018-10, with the labels that each got.

#552 Update add on resizer
  kubernetes/kube-state-metrics-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#549 Add changelog note for breaking change in #371
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#553 Fix link href
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#534 pkg/collectors: Introduce MetricsStore updated by Reflectors
  .travis.yml
  Documentation/design/metrics-store-performance-optimization.md
  main.go
  main_test.go
  pkg/collectors/builder.go
  pkg/collectors/collectors.go
  pkg/collectors/configmap.go
  pkg/collectors/configmap_test.go
  pkg/collectors/cronjob.go
  pkg/collectors/cronjob_test.go
  pkg/collectors/daemonset.go
  pkg/collectors/daemonset_test.go
  pkg/collectors/deployment.go
  pkg/collectors/deployment_test.go
  pkg/collectors/endpoint.go
  pkg/collectors/endpoint_test.go
  pkg/collectors/hpa.go
  pkg/collectors/hpa_test.go
  pkg/collectors/job.go
  pkg/collectors/job_test.go
  pkg/collectors/limitrange.go
  pkg/collectors/limitrange_test.go
  pkg/collectors/namespace.go
  pkg/collectors/namespace_test.go
  pkg/collectors/node.go
  pkg/collectors/node_test.go
  pkg/collectors/persistentvolume.go
  pkg/collectors/persistentvolume_test.go
  pkg/collectors/persistentvolumeclaim.go
  pkg/collectors/persistentvolumeclaim_test.go
  pkg/collectors/pod.go
  pkg/collectors/pod_test.go
  pkg/collectors/replicaset.go
  pkg/collectors/replicaset_test.go
  pkg/collectors/replicationcontroller.go
  pkg/collectors/replicationcontroller_test.go
  pkg/collectors/resourcequota.go
  pkg/collectors/resourcequota_test.go
  pkg/collectors/secret.go
  pkg/collectors/secret_test.go
  pkg/collectors/service.go
  pkg/collectors/service_test.go
  pkg/collectors/statefulset.go
  pkg/collectors/statefulset_test.go
  pkg/collectors/testutils.go
  pkg/collectors/testutils/testutils.go
  pkg/metrics/metrics.go
  pkg/metrics_store/metrics_store.go
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#562 README: Update compatibility matrix to include 1.12
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#551 Add PodDisruptionBudget metrics
  Documentation/README.md
  Documentation/poddisruptionbudget-metrics.md
  kubernetes/kube-state-metrics-cluster-role.yaml
  pkg/collectors/builder.go
  pkg/collectors/poddisruptionbudget.go
  pkg/collectors/poddisruptionbudget_test.go
  pkg/options/collector.go
  tests/manifests/poddisruptionbudget.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#566 Pre-allocate the metrics slice in `GetAll`
  pkg/metrics_store/metrics_store.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#564 update documentation to reflect case-sensitivity issues in gcloud
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#565 README.md: Remove reference to Prometheus client_golang library
  README.md
Labels: approved, cncf-cla: yes, lgtm

#567 pkg/metrics: Tune NewMetrics function
  pkg/collectors/testutils.go
  pkg/collectors/testutils_test.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#572 pkg/metrics: Write newline as byte with strings.Builder
  pkg/metrics/metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
