Repository kubernetes/kube-state-metrics, pull requests merged in 2018-07, with the labels that each got.

#484 Add dynamic volume
  pkg/collectors/node.go
  pkg/collectors/pod.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#462 Add note about CPU limits
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#485 Typo fix:PersistentVolumeClaim->PersistentVolume
  Documentation/persistentvolume-metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#489 Upgrade go version
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#487 collectors: Change job label to job_name
  CHANGELOG.md
  pkg/collectors/job.go
  pkg/collectors/job_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#491 Fix typo in metric description
  pkg/collectors/pod.go
  pkg/collectors/pod_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#490 add description about pod nanny
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#488 Allow white- and blacklisting metrics to be exposed
  CHANGELOG.md
  main.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/options/options.go
  pkg/options/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#496 add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/M
