Repository kubernetes/kube-state-metrics, pull requests merged in 2018-09, with the labels that each got.

#538 Change error message
  main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#539 add an example of joining the metrics in docs
  Documentation/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#545 Export stateful sets status.{current_revision,update_revision}
  Documentation/statefulset-metrics.md
  pkg/collectors/statefulset.go
  pkg/collectors/statefulset_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
