Repository kubernetes/kube-state-metrics, pull requests merged in 2018-11, with the labels that each got.

#575 Making kube-state-metrics a library
  pkg/collectors/builder.go
  pkg/collectors/collectors.go
  pkg/collectors/configmap.go
  pkg/collectors/cronjob.go
  pkg/collectors/daemonset.go
  pkg/collectors/deployment.go
  pkg/collectors/endpoint.go
  pkg/collectors/hpa.go
  pkg/collectors/job.go
  pkg/collectors/limitrange.go
  pkg/collectors/namespace.go
  pkg/collectors/node.go
  pkg/collectors/persistentvolume.go
  pkg/collectors/persistentvolumeclaim.go
  pkg/collectors/pod.go
  pkg/collectors/poddisruptionbudget.go
  pkg/collectors/replicaset.go
  pkg/collectors/replicationcontroller.go
  pkg/collectors/resourcequota.go
  pkg/collectors/secret.go
  pkg/collectors/service.go
  pkg/collectors/statefulset.go
  pkg/collectors/utils.go
  pkg/metrics/metric_family.go
  tests/e2e.sh
  tests/lib/lib_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#578 Adding CreateContainerConfigError as possible reason for container no…
  pkg/collectors/pod.go
  pkg/collectors/pod_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#571 Add external name/ip and load balancer ingress to service collector
  Documentation/service-metrics.md
  pkg/collectors/service.go
  pkg/collectors/service_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#582 Correct readme Deployment -> Development typo
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#581 Fix typos: cleaup -> cleanup
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#586 pkg/metrics_store: Cache objects by uid not name
  pkg/metrics_store/metrics_store.go
  pkg/metrics_store/metrics_store_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#577 pkg/collectors: Renable white-/blacklisting and HELP text
  .travis.yml
  main.go
  main_test.go
  pkg/collectors/builder.go
  pkg/collectors/collectors.go
  pkg/collectors/configmap.go
  pkg/collectors/configmap_test.go
  pkg/collectors/cronjob.go
  pkg/collectors/cronjob_test.go
  pkg/collectors/daemonset.go
  pkg/collectors/daemonset_test.go
  pkg/collectors/deployment.go
  pkg/collectors/deployment_test.go
  pkg/collectors/endpoint.go
  pkg/collectors/endpoint_test.go
  pkg/collectors/hpa.go
  pkg/collectors/hpa_test.go
  pkg/collectors/job.go
  pkg/collectors/job_test.go
  pkg/collectors/limitrange.go
  pkg/collectors/limitrange_test.go
  pkg/collectors/namespace.go
  pkg/collectors/namespace_test.go
  pkg/collectors/node.go
  pkg/collectors/node_test.go
  pkg/collectors/persistentvolume.go
  pkg/collectors/persistentvolume_test.go
  pkg/collectors/persistentvolumeclaim.go
  pkg/collectors/persistentvolumeclaim_test.go
  pkg/collectors/pod.go
  pkg/collectors/pod_test.go
  pkg/collectors/poddisruptionbudget.go
  pkg/collectors/poddisruptionbudget_test.go
  pkg/collectors/replicaset.go
  pkg/collectors/replicaset_test.go
  pkg/collectors/replicationcontroller.go
  pkg/collectors/replicationcontroller_test.go
  pkg/collectors/resourcequota.go
  pkg/collectors/resourcequota_test.go
  pkg/collectors/secret.go
  pkg/collectors/secret_test.go
  pkg/collectors/service.go
  pkg/collectors/service_test.go
  pkg/collectors/statefulset.go
  pkg/collectors/statefulset_test.go
  pkg/collectors/testutils.go
  pkg/collectors/utils.go
  pkg/metrics/metric_family.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/metrics_store/metrics_store.go
  pkg/metrics_store/metrics_store_test.go
  pkg/whiteblacklist/whiteblacklist.go
  pkg/whiteblacklist/whiteblacklist_test.go
  tests/lib/lib_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#587 main_test.go: Extend pod fixture and fix bench set bytes
  main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#588 pkg/builder: Make collector order deterministic
  main.go
  main_test.go
  pkg/collectors/builder.go
  pkg/options/types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#590 pkg/collectors: Refactor deployment and daemonset
  main_test.go
  pkg/collectors/builder.go
  pkg/collectors/daemonset.go
  pkg/collectors/daemonset_test.go
  pkg/collectors/deployment.go
  pkg/collectors/deployment_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#592 pkg/collectors: Refactor job and limit range collector
  main_test.go
  pkg/collectors/builder.go
  pkg/collectors/job.go
  pkg/collectors/job_test.go
  pkg/collectors/limitrange.go
  pkg/collectors/limitrange_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#593 pkg/collectors: Refactor namespace and node collector
  main.go
  main_test.go
  pkg/collectors/builder.go
  pkg/collectors/namespace.go
  pkg/collectors/namespace_test.go
  pkg/collectors/node.go
  pkg/collectors/node_test.go
  pkg/collectors/testutils.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#589 pkg/collectors: Refactor Cron Job and Config Map collector
  main_test.go
  pkg/collectors/builder.go
  pkg/collectors/configmap.go
  pkg/collectors/configmap_test.go
  pkg/collectors/cronjob.go
  pkg/collectors/cronjob_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#595 pkg/collectors: Refactor pod disruption budget and replica set collector
  main_test.go
  pkg/collectors/builder.go
  pkg/collectors/poddisruptionbudget.go
  pkg/collectors/poddisruptionbudget_test.go
  pkg/collectors/replicaset.go
  pkg/collectors/replicaset_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#597 pkg/collectors: Refactor secret and stateful set collector
  main_test.go
  pkg/collectors/builder.go
  pkg/collectors/secret.go
  pkg/collectors/secret_test.go
  pkg/collectors/statefulset.go
  pkg/collectors/statefulset_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#596 pkg/collectors: Refactor replication controller and resource quota collector
  main_test.go
  pkg/collectors/builder.go
  pkg/collectors/replicationcontroller.go
  pkg/collectors/replicationcontroller_test.go
  pkg/collectors/resourcequota.go
  pkg/collectors/resourcequota_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#591 pkg/collectors: Refactor endpoint and hpa collector
  .travis.yml
  main_test.go
  pkg/collectors/builder.go
  pkg/collectors/endpoint.go
  pkg/collectors/endpoint_test.go
  pkg/collectors/hpa.go
  pkg/collectors/hpa_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#598 *: Reintroduce TYPE text
  main_test.go
  pkg/collectors/builder.go
  pkg/collectors/configmap.go
  pkg/collectors/cronjob.go
  pkg/collectors/daemonset.go
  pkg/collectors/deployment.go
  pkg/collectors/endpoint.go
  pkg/collectors/hpa.go
  pkg/collectors/job.go
  pkg/collectors/limitrange.go
  pkg/collectors/namespace.go
  pkg/collectors/node.go
  pkg/collectors/persistentvolume.go
  pkg/collectors/persistentvolumeclaim.go
  pkg/collectors/pod.go
  pkg/collectors/poddisruptionbudget.go
  pkg/collectors/replicaset.go
  pkg/collectors/replicationcontroller.go
  pkg/collectors/resourcequota.go
  pkg/collectors/secret.go
  pkg/collectors/service.go
  pkg/collectors/statefulset.go
  pkg/metrics/metrics.go
  pkg/metrics_store/metrics_store.go
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#601 Merge performance optimization into master
  .travis.yml
  main.go
  main_test.go
  pkg/collectors/builder.go
  pkg/collectors/collectors.go
  pkg/collectors/configmap.go
  pkg/collectors/configmap_test.go
  pkg/collectors/cronjob.go
  pkg/collectors/cronjob_test.go
  pkg/collectors/daemonset.go
  pkg/collectors/daemonset_test.go
  pkg/collectors/deployment.go
  pkg/collectors/deployment_test.go
  pkg/collectors/endpoint.go
  pkg/collectors/endpoint_test.go
  pkg/collectors/hpa.go
  pkg/collectors/hpa_test.go
  pkg/collectors/job.go
  pkg/collectors/job_test.go
  pkg/collectors/limitrange.go
  pkg/collectors/limitrange_test.go
  pkg/collectors/namespace.go
  pkg/collectors/namespace_test.go
  pkg/collectors/node.go
  pkg/collectors/node_test.go
  pkg/collectors/persistentvolume.go
  pkg/collectors/persistentvolume_test.go
  pkg/collectors/persistentvolumeclaim.go
  pkg/collectors/persistentvolumeclaim_test.go
  pkg/collectors/pod.go
  pkg/collectors/pod_test.go
  pkg/collectors/poddisruptionbudget.go
  pkg/collectors/poddisruptionbudget_test.go
  pkg/collectors/replicaset.go
  pkg/collectors/replicaset_test.go
  pkg/collectors/replicationcontroller.go
  pkg/collectors/replicationcontroller_test.go
  pkg/collectors/resourcequota.go
  pkg/collectors/resourcequota_test.go
  pkg/collectors/secret.go
  pkg/collectors/secret_test.go
  pkg/collectors/service.go
  pkg/collectors/service_test.go
  pkg/collectors/statefulset.go
  pkg/collectors/statefulset_test.go
  pkg/collectors/testutils.go
  pkg/collectors/utils.go
  pkg/metrics/metric_family.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/metrics_store/metrics_store.go
  pkg/metrics_store/metrics_store_test.go
  pkg/options/types.go
  pkg/whiteblacklist/whiteblacklist.go
  pkg/whiteblacklist/whiteblacklist_test.go
  tests/e2e.sh
  tests/lib/lib_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#607 *: Cut v1.5.0-alpha.0
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#608 tests: Add stability notice to lib pkg
  tests/lib/doc.go
  tests/lib/lib_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
