Repository kubernetes/kube-state-metrics, pull requests merged in 2018-12, with the labels that each got.

#609 tests: Add stability notice to lib pkg - back to master
  tests/lib/doc.go
  tests/lib/lib_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#615 fix go fmt check
  .travis.yml
  Makefile
  pkg/collectors/builder.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#617 *: Cut v1.5.0-beta.0
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#616 Add labels in Exposed Metrics documentation
  Documentation/node-metrics.md
  Documentation/pod-metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#618 Clear TODO comment in builder.go
  main.go
  pkg/collectors/builder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#614 exchange heapster status
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#620 pkg/collectors: Remove leftover commented code
  pkg/collectors/builder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#621 Cleanup whitespace in Kuberernetes manifest files
  kubernetes/kube-state-metrics-cluster-role-binding.yaml
  kubernetes/kube-state-metrics-role-binding.yaml
  kubernetes/kube-state-metrics-role.yaml
  kubernetes/kube-state-metrics-service-account.yaml
  kubernetes/kube-state-metrics-service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
