Repository kubernetes/kube-state-metrics, pull requests merged in 2019-03, with the labels that each got.

#690 improve the release documentation
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#692 Fixes typo in README.md from Secrects to Secrets
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#693 fix all golint and gosimple issues in kube-state-metrics
  internal/collector/builder.go
  internal/collector/configmap.go
  internal/collector/cronjob.go
  internal/collector/daemonset.go
  internal/collector/deployment.go
  internal/collector/endpoint.go
  internal/collector/hpa.go
  internal/collector/ingress.go
  internal/collector/job.go
  internal/collector/limitrange.go
  internal/collector/namespace.go
  internal/collector/node.go
  internal/collector/persistentvolume.go
  internal/collector/persistentvolumeclaim.go
  internal/collector/pod.go
  internal/collector/poddisruptionbudget.go
  internal/collector/replicaset.go
  internal/collector/replicaset_test.go
  internal/collector/replicationcontroller.go
  internal/collector/replicationcontroller_test.go
  internal/collector/resourcequota.go
  internal/collector/secret.go
  internal/collector/service.go
  internal/collector/statefulset.go
  pkg/constant/resource_unit.go
  pkg/metric/generator.go
  pkg/metric/metric.go
  pkg/metrics_store/metrics_store.go
  pkg/options/collector.go
  pkg/options/options.go
  pkg/options/types.go
  pkg/version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#695 lint: add golangci-lint to the CI pipeline of kube-state-metrics
  .golangci.yml
  .travis.yml
  Makefile
  internal/collector/configmap.go
  internal/collector/configmap_test.go
  internal/collector/cronjob_test.go
  internal/collector/endpoint.go
  internal/collector/endpoint_test.go
  internal/collector/hpa_test.go
  internal/collector/job_test.go
  internal/collector/limitrange.go
  internal/collector/limitrange_test.go
  internal/collector/namespace.go
  internal/collector/namespace_test.go
  internal/collector/node_test.go
  internal/collector/persistentvolume.go
  internal/collector/persistentvolume_test.go
  internal/collector/persistentvolumeclaim.go
  internal/collector/persistentvolumeclaim_test.go
  internal/collector/replicationcontroller.go
  internal/collector/replicationcontroller_test.go
  internal/collector/resourcequota.go
  internal/collector/resourcequota_test.go
  internal/collector/secret.go
  internal/collector/secret_test.go
  internal/collector/service.go
  internal/collector/service_test.go
  main_test.go
  pkg/metrics_store/metrics_store_test.go
  tests/lib/lib_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#698 Update embargo doc link in SECURITY_CONTACTS and change PST to PSC
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#696 [Documentation] Add join metric example for running pods requesting memory
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#700 update go version to 1.12.x
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#650 Add collector for csr
  docs/README.md
  docs/certificatessigningrequest-metrics.md
  internal/collector/builder.go
  internal/collector/certificatesigningrequest.go
  internal/collector/certificatesigningrequest_test.go
  pkg/options/collector.go
  tests/manifests/csr.yaml
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#705 Fix metric labels for kube_job_failed
  internal/collector/job.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
