Repository kubernetes/kube-state-metrics, pull requests merged in 2019-02, with the labels that each got.

#645 Enable use as kustomize base layer
  kubernetes/kube-state-metrics-cluster-role.yaml
  kubernetes/kube-state-metrics-deployment.yaml
  kubernetes/kube-state-metrics-role.yaml
  kubernetes/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#652 use the appsv1 package as it is more appropriate for deployment runtimeObject
  internal/collector/deployment.go
  internal/collector/deployment_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#655 correct some typographical mistakes in kube-state-metrics
  .travis.yml
  Documentation/design/metrics-store-performance-optimization.md
  Documentation/horizontalpodautoscaler-metrics.md
  README.md
  main.go
  pkg/options/types.go
  pkg/whiteblacklist/whiteblacklist.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#644 pkg/metric/generator: Refactor GenerateFunc call and return pointer
  internal/collector/configmap.go
  internal/collector/cronjob.go
  internal/collector/daemonset.go
  internal/collector/deployment.go
  internal/collector/endpoint.go
  internal/collector/hpa.go
  internal/collector/job.go
  internal/collector/limitrange.go
  internal/collector/namespace.go
  internal/collector/node.go
  internal/collector/persistentvolume.go
  internal/collector/persistentvolumeclaim.go
  internal/collector/pod.go
  internal/collector/poddisruptionbudget.go
  internal/collector/replicaset.go
  internal/collector/replicationcontroller.go
  internal/collector/resourcequota.go
  internal/collector/secret.go
  internal/collector/service.go
  internal/collector/statefulset.go
  pkg/metric/generator.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#654 Move kustomization.yaml
  kubernetes/kustomization.yaml
  kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#657 documentation fixes: i)minor improvements ii)add new hpa labels in do…
  Documentation/README.md
  Documentation/horizontalpodautoscaler-metrics.md
  Documentation/node-metrics.md
  Documentation/pod-metrics.md
  internal/collector/hpa_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#640 add ingress labels
  Documentation/README.md
  Documentation/ingress-metrics.md
  internal/collector/builder.go
  internal/collector/ingress.go
  internal/collector/ingress_test.go
  pkg/options/collector.go
  tests/manifests/ingress.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#660 README.md: Reword raw data section
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#663 add the ingress resource to the extensions apigroup section of RBAC
  kubernetes/kube-state-metrics-cluster-role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#662 adding the CI check for go modules consistency
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#666 Changed the collector name from ingress to ingresses to match the convention
  internal/collector/builder.go
  pkg/options/collector.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#664 add shellcheck to the ci and minor cleanup of bash scripts in kube_state_metrics
  .travis.yml
  Makefile
  tests/check_license.sh
  tests/compare_benchmarks.sh
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#669 update Dockerfile to use latest alpine
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#670 fix the release documentation
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#671 use cancelable context instead of context.TODO()
  main.go
  main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#676 use klog instead of glog
  go.mod
  go.sum
  internal/collector/builder.go
  main.go
  pkg/options/options.go
  tests/e2e.sh
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#673 add pvc access mode metric
  Documentation/persistentvolumeclaim-metrics.md
  internal/collector/persistentvolumeclaim.go
  internal/collector/persistentvolumeclaim_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#677 docs: rename the Documentation folder to docs
  Makefile
  README.md
  docs/README.md
  docs/configmap-metrics.md
  docs/cronjob-metrics.md
  docs/daemonset-metrics.md
  docs/deployment-metrics.md
  docs/design/metrics-store-performance-optimization.md
  docs/endpoint-metrics.md
  docs/horizontalpodautoscaler-metrics.md
  docs/ingress-metrics.md
  docs/job-metrics.md
  docs/limitrange-metrics.md
  docs/namespace-metrics.md
  docs/node-metrics.md
  docs/persistentvolume-metrics.md
  docs/persistentvolumeclaim-metrics.md
  docs/pod-metrics.md
  docs/poddisruptionbudget-metrics.md
  docs/replicaset-metrics.md
  docs/replicationcontroller-metrics.md
  docs/resourcequota-metrics.md
  docs/secret-metrics.md
  docs/service-metrics.md
  docs/statefulset-metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#675 Update metric-server documentation in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#679 add tariq1890 to the reviewers list
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#674 add persistent volume capacity metric
  docs/persistentvolume-metrics.md
  internal/collector/persistentvolume.go
  internal/collector/persistentvolume_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#681 Export Job's owner
  docs/job-metrics.md
  internal/collector/job.go
  internal/collector/job_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#686 Revert "Do not export Job's owner metrics if Job's OwnerReference is …
  internal/collector/job.go
  internal/collector/job_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#688 replace git describe with VERSION file for maintaining version tagging
  Makefile
  VERSION
Labels: approved, cncf-cla: yes, lgtm, size/XS

#689 improve the variable name of the kube state metrics image tag in e2e shell script
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
