Repository kubernetes/kube-state-metrics, pull requests merged in 2019-11, with the labels that each got.

#963 expose the PodCIDR in node info
  internal/store/node.go
  internal/store/node_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#965 document the new pod-cidr dimension
  docs/node-metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#961 add hpa stats for current utilization and average value
  docs/horizontalpodautoscaler-metrics.md
  internal/store/hpa.go
  internal/store/hpa_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#966 Added a kube_hpa_target_metric metric that publishes all of a HPA's target metrics.
  docs/horizontalpodautoscaler-metrics.md
  internal/store/hpa.go
  internal/store/hpa_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#971 fixing some issues missed during previous code reviews
  docs/horizontalpodautoscaler-metrics.md
  docs/namespace-metrics.md
  internal/store/hpa.go
  internal/store/hpa_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#968 adding Evicted to reasons terminated
  internal/store/pod.go
  internal/store/pod_test.go
  main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S
