Repository kubernetes/kube-state-metrics, pull requests merged in 2019-05, with the labels that each got.

#736 Capital letters for ENDPOINT string
  docs/endpoint-metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#737 Add additional ingress metrics
  docs/ingress-metrics.md
  internal/collector/ingress.go
  internal/collector/ingress_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#738 *: Cut v1.6.0
  CHANGELOG.md
  VERSION
Labels: approved, cncf-cla: yes, lgtm, size/S

#739 *: Merge release-1.6 back into master
  CHANGELOG.md
  VERSION
  kubernetes/kube-state-metrics-deployment.yaml
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#740 Add DeadlineExceeded pod termination reason
  docs/pod-metrics.md
  internal/collector/pod.go
  internal/collector/pod_test.go
  main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#741 update documentation to reflect the latest release of kube-state-metrics
  README.md
  kubernetes/kube-state-metrics-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#742 collector: De-duplicate common code for building collectors
  internal/collector/builder.go
  internal/collector/certificatesigningrequest.go
  internal/collector/configmap.go
  internal/collector/cronjob.go
  internal/collector/daemonset.go
  internal/collector/deployment.go
  internal/collector/endpoint.go
  internal/collector/hpa.go
  internal/collector/ingress.go
  internal/collector/job.go
  internal/collector/limitrange.go
  internal/collector/namespace.go
  internal/collector/node.go
  internal/collector/persistentvolume.go
  internal/collector/persistentvolumeclaim.go
  internal/collector/pod.go
  internal/collector/poddisruptionbudget.go
  internal/collector/replicaset.go
  internal/collector/replicationcontroller.go
  internal/collector/resourcequota.go
  internal/collector/secret.go
  internal/collector/service.go
  internal/collector/statefulset.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#750 kubernetes/deployment.yaml: Remove addon resizer
  README.md
  kubernetes/kube-state-metrics-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#749 chore: bump versions of prometheus, golangci, and minikube
  Makefile
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#748 use distroless/static as base image to further reduce image size
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#756 use latest version of k8s.io/klog
  go.mod
  go.sum
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#757 CLI arguments and limited privileges environment documentation
  .gitignore
  Makefile
  README.md
  docs/README.md
  docs/cli-arguments.md
  scripts/generate-help-text.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#755 lint: fix gocritic issues and add gocritic linter
  .golangci.yml
  internal/collector/cronjob.go
  internal/collector/pod.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#758 kube-state-metrics-resizer role is no longer needed
  kubernetes/kube-state-metrics-role-binding.yaml
  kubernetes/kube-state-metrics-role.yaml
  kustomization.yaml
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#763 Add CreateContainerError and InvalidImageName waiting reasons
  docs/pod-metrics.md
  internal/collector/pod.go
  internal/collector/pod_test.go
  main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#765 Cherry-Pick for 1.6: update documentation to reflect the latest release of kube-state-metrics
  README.md
  kubernetes/kube-state-metrics-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#764 Delete prometheus config url which has been out of date
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#762 Add pod init container metrics
  docs/pod-metrics.md
  internal/collector/pod.go
  internal/collector/pod_test.go
  main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#769 Add note on costing to README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#767 return standardized text for health endpoint
  main.go
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#774 trivial updates to README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#772 OWNERS: Add tariq1890 as approver
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS
