Repository kubernetes/kube-state-metrics, pull requests merged in 2019-12, with the labels that each got.

#983 remove client-go column from support version matrix
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#969 Multi list watch
  internal/store/builder.go
  pkg/listwatch/listwatch.go
  pkg/listwatch/namespace_denylist.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#984 *: cut v1.9.0-rc.0
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#962 Add kube-state-metrics own alerting rules
  .travis.yml
  Makefile
  examples/prometheus-alerting-rules/alerts.yaml
  jsonnet/kube-state-metrics-mixin/alerts.libsonnet
  jsonnet/kube-state-metrics-mixin/mixin.libsonnet
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
  scripts/jsonnetfile.json
  scripts/jsonnetfile.lock.json
  scripts/mixin.jsonnet
Labels: approved, cncf-cla: yes, lgtm, size/L

#985 Add kube-state-metrics mixin to v1.9.0-rc.0
  .travis.yml
  CHANGELOG.md
  Makefile
  examples/prometheus-alerting-rules/alerts.yaml
  jsonnet/kube-state-metrics-mixin/alerts.libsonnet
  jsonnet/kube-state-metrics-mixin/mixin.libsonnet
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
  scripts/jsonnetfile.json
  scripts/jsonnetfile.lock.json
  scripts/mixin.jsonnet
Labels: approved, cncf-cla: yes, lgtm, size/L

#986 jsonnet/kube-state-metrics-mixin/alerts.libsonnet: Fix selector typo
  jsonnet/kube-state-metrics-mixin/alerts.libsonnet
Labels: approved, cncf-cla: yes, lgtm, size/XS

#987 jsonnet/kube-state-metrics-mixin/alerts.libsonnet: Fix selector typo
  jsonnet/kube-state-metrics-mixin/alerts.libsonnet
Labels: approved, cncf-cla: yes, lgtm, size/XS

#993 fix nil panics parsing hpa cpu current metrics
  internal/store/hpa.go
  internal/store/hpa_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#994 Add PR #962 to the v1.9.0-rc.0 CHANGELOG
  CHANGELOG.md
  internal/store/hpa.go
  internal/store/hpa_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#997 Move resource version from metric label to metric number value
  CHANGELOG.md
  docs/configmap-metrics.md
  docs/ingress-metrics.md
  docs/mutatingwebhookconfiguration.md
  docs/secret-metrics.md
  docs/validatingwebhookconfiguration.md
  internal/store/configmap.go
  internal/store/configmap_test.go
  internal/store/ingress.go
  internal/store/ingress_test.go
  internal/store/mutatingwebhookconfiguration.go
  internal/store/mutatingwebhookconfiguration_test.go
  internal/store/secret.go
  internal/store/secret_test.go
  internal/store/utils.go
  internal/store/validatingwebhookconfiguration.go
  internal/store/validatingwebhookconfiguration_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#998 CHANGELOG.md: Fix date and rc number in changelog
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#999 VERSION: Update version to 1.9.0-rc.1
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1010 *: Cut release 1.9.0
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
  scripts/jsonnetfile.lock.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#1011 *: Merge in release-1.9 changes to master
  CHANGELOG.md
  README.md
  VERSION
  docs/configmap-metrics.md
  docs/ingress-metrics.md
  docs/mutatingwebhookconfiguration.md
  docs/secret-metrics.md
  docs/validatingwebhookconfiguration.md
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
  internal/store/configmap.go
  internal/store/configmap_test.go
  internal/store/ingress.go
  internal/store/ingress_test.go
  internal/store/mutatingwebhookconfiguration.go
  internal/store/mutatingwebhookconfiguration_test.go
  internal/store/secret.go
  internal/store/secret_test.go
  internal/store/utils.go
  internal/store/validatingwebhookconfiguration.go
  internal/store/validatingwebhookconfiguration_test.go
  scripts/jsonnetfile.lock.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#1014 internal/store/hpa.go: fix nil panics when parsing hpa memory current metrics
  internal/store/hpa.go
  internal/store/hpa_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S
