Repository kubernetes/kube-state-metrics, pull requests merged in 2019-08, with the labels that each got.

#856 OWNERS: Removing mxinden
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#858 Add liveness and readiness probe in deployment file
  kubernetes/kube-state-metrics-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#860 *: cut v1.7.2 release
  CHANGELOG.md
  README.md
  VERSION
  kubernetes/kube-state-metrics-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#861 add LiLiC as approver
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#863 SECURITY_CONTACTS: Update list to reflect the mantainers
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#835 feat: add kube_pod_status_unschedulable metric
  docs/pod-metrics.md
  internal/store/pod.go
  internal/store/pod_test.go
  main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#867 Makefile: Remove tmpdir after container build
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#869 lint: enforce goimports local prefixes
  .golangci.yml
  internal/store/builder.go
  internal/store/certificatesigningrequest_test.go
  internal/store/configmap.go
  internal/store/configmap_test.go
  internal/store/cronjob.go
  internal/store/cronjob_test.go
  internal/store/daemonset.go
  internal/store/daemonset_test.go
  internal/store/deployment_test.go
  internal/store/endpoint.go
  internal/store/endpoint_test.go
  internal/store/hpa_test.go
  internal/store/ingress_test.go
  internal/store/job_test.go
  internal/store/limitrange.go
  internal/store/limitrange_test.go
  internal/store/namespace_test.go
  internal/store/node_test.go
  internal/store/persistentvolume_test.go
  internal/store/persistentvolumeclaim_test.go
  internal/store/pod_test.go
  internal/store/poddisruptionbudget.go
  internal/store/poddisruptionbudget_test.go
  internal/store/replicaset_test.go
  internal/store/replicationcontroller.go
  internal/store/replicationcontroller_test.go
  internal/store/resourcequota.go
  internal/store/resourcequota_test.go
  internal/store/secret.go
  internal/store/secret_test.go
  internal/store/service.go
  internal/store/service_test.go
  internal/store/statefulset_test.go
  internal/store/storageclass_test.go
  internal/store/utils.go
  internal/store/verticalpodautoscaler.go
  internal/store/verticalpodautoscaler_test.go
  tests/lib/lib_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#866 *: Add list/watch success/error count total metrics
  README.md
  internal/store/builder.go
  main.go
  main_test.go
  pkg/watch/watch.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#874 use MustRegister instead of Register
  main.go
  pkg/watch/watch.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#613 Introduce sharding (and experimental auto-sharding)
  README.md
  docs/cli-arguments.md
  go.mod
  go.sum
  internal/store/builder.go
  kubernetes/autosharding/kube-state-metrics-cluster-role-binding.yaml
  kubernetes/autosharding/kube-state-metrics-cluster-role.yaml
  kubernetes/autosharding/kube-state-metrics-role-binding.yaml
  kubernetes/autosharding/kube-state-metrics-role.yaml
  kubernetes/autosharding/kube-state-metrics-service-account.yaml
  kubernetes/autosharding/kube-state-metrics-statefulset.yaml
  main.go
  main_test.go
  pkg/metricshandler/metrics_handler.go
  pkg/options/options.go
  pkg/sharding/listwatch.go
  pkg/sharding/listwatch_test.go
  tests/compare-sharding.sh
  vendor/github.com/dgryski/go-jump/LICENSE
  vendor/github.com/dgryski/go-jump/README.md
  vendor/github.com/dgryski/go-jump/jump.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XL
