Repository kubernetes/kube-state-metrics, pull requests merged in 2019-10, with the labels that each got.

#909 VERSION: Update version to v1.8.0-rc.1
  VERSION
Labels: approved, cncf-cla: yes, lgtm, size/XS

#910 *: cut v1.8.0
  CHANGELOG.md
  README.md
  VERSION
  kubernetes/autosharding/kube-state-metrics-statefulset.yaml
  kubernetes/kube-state-metrics-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#911 Merge release-1.8 into master
  CHANGELOG.md
  README.md
  VERSION
  kubernetes/autosharding/kube-state-metrics-statefulset.yaml
  kubernetes/kube-state-metrics-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#912 Update README
  README.md
Labels: approved, cncf-cla: yes, hacktoberfest, lgtm, size/XS

#926 Update golangci version to latest stable 1.19.1
  Makefile
Labels: approved, cncf-cla: yes, hacktoberfest, lgtm, size/XS

#921 Add godoc badge to README.md #916
  README.md
Labels: approved, cncf-cla: yes, hacktoberfest, lgtm, size/XS

#928 fix a broken link to './kubernetes/autosharding'
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#914 Add support for MutatingWebhookConfiguration +ValidatingWebhookConfiguration
  docs/README.md
  docs/cli-arguments.md
  docs/mutatingwebhookconfiguration.md
  docs/validatingwebhookconfiguration.md
  examples/standard/cluster-role.yaml
  internal/store/builder.go
  internal/store/mutatingwebhookconfiguration.go
  internal/store/mutatingwebhookconfiguration_test.go
  internal/store/validatingwebhookconfiguration.go
  internal/store/validatingwebhookconfiguration_test.go
  pkg/options/collector.go
  tests/manifests/mutatingwebhookconfiguration.yaml
  tests/manifests/validatingwebhookconfiguration.yaml
Labels: approved, cncf-cla: yes, hacktoberfest, lgtm, size/XL

#929 Add check for ReclaimPolicy, VolumeBindingMode storageclass metrics.
  internal/store/storageclass.go
  internal/store/storageclass_test.go
  tests/manifests/storageclass.yaml
Labels: approved, cncf-cla: yes, hacktoberfest, lgtm, size/M

#934 Enable unconvert linter
  .golangci.yml
  internal/store/configmap.go
  internal/store/ingress.go
  internal/store/mutatingwebhookconfiguration.go
  internal/store/secret.go
  internal/store/utils.go
  internal/store/validatingwebhookconfiguration.go
  pkg/metrics_store/metrics_store.go
Labels: approved, cncf-cla: yes, hacktoberfest, lgtm, size/S

#933 adds slack channel link to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, hacktoberfest, lgtm, size/XS

#935 Remove unnecessary type conversion
  pkg/metric/metric_test.go
  pkg/metricshandler/metrics_handler.go
  pkg/sharding/listwatch.go
Labels: approved, cncf-cla: yes, hacktoberfest, lgtm, size/XS

#936 Pre-allocation of slices
  pkg/options/types.go
  pkg/whiteblacklist/whiteblacklist.go
Labels: approved, cncf-cla: yes, hacktoberfest, lgtm, size/S

#938 Fix typo in the job metrics description
  docs/job-metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#940 [documentation] Adding a new Kubernetes Resource
  README.md
  docs/developer/guide.md
Labels: approved, cncf-cla: yes, hacktoberfest, lgtm, size/S

#946 add VolumeAttachment collector
  docs/README.md
  docs/cli-arguments.md
  docs/volumeattachment-metrics.md
  examples/autosharding/cluster-role.yaml
  examples/standard/cluster-role.yaml
  internal/store/builder.go
  internal/store/utils.go
  internal/store/volumeattachment.go
  internal/store/volumeattachment_test.go
  pkg/options/collector.go
  tests/manifests/volumeattachment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#893 store: collector for NetworkPolicy objects
  Makefile
  docs/README.md
  docs/cli-arguments.md
  docs/networkpolicy-metrics.md
  examples/autosharding/cluster-role.yaml
  examples/standard/cluster-role.yaml
  go.mod
  go.sum
  internal/store/builder.go
  internal/store/networkpolicy.go
  internal/store/networkpolicy_test.go
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
  pkg/options/collector.go
  tests/manifests/networkpolicy.yaml
  tools.go
  vendor/github.com/brancz/gojsontoyaml/.gitignore
  vendor/github.com/brancz/gojsontoyaml/Gopkg.lock
  vendor/github.com/brancz/gojsontoyaml/Gopkg.toml
  vendor/github.com/brancz/gojsontoyaml/LICENSE
  vendor/github.com/brancz/gojsontoyaml/README.md
  vendor/github.com/brancz/gojsontoyaml/go.mod
  vendor/github.com/brancz/gojsontoyaml/go.sum
  vendor/github.com/brancz/gojsontoyaml/main.go
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#954 clean up go mod indirect entries
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/errors.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/gogo/protobuf/LICENSE
  vendor/github.com/gogo/protobuf/proto/encode.go
  vendor/github.com/gogo/protobuf/proto/lib.go
  vendor/github.com/gogo/protobuf/proto/pointer_unsafe_gogo.go
  vendor/github.com/gogo/protobuf/proto/properties.go
  vendor/github.com/gogo/protobuf/proto/table_marshal.go
  vendor/github.com/gogo/protobuf/proto/table_unmarshal.go
  vendor/github.com/gogo/protobuf/proto/text.go
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/github.com/gogo/protobuf/proto/wrappers.go
  vendor/github.com/gogo/protobuf/proto/wrappers_gogo.go
  vendor/github.com/gophercloud/gophercloud/.travis.yml
  vendor/github.com/gophercloud/gophercloud/.zuul.yaml
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/auth_result.go
  vendor/github.com/gophercloud/gophercloud/doc.go
  vendor/github.com/gophercloud/gophercloud/errors.go
  vendor/github.com/gophercloud/gophercloud/go.mod
  vendor/github.com/gophercloud/gophercloud/go.sum
  vendor/github.com/gophercloud/gophercloud/openstack/auth_env.go
  vendor/github.com/gophercloud/gophercloud/openstack/client.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/github.com/gophercloud/gophercloud/service_client.go
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/golang.org/x/oauth2/google/google.go
  vendor/golang.org/x/oauth2/jwt/jwt.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/OWNERS
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#955 move tools.go to the right directory
  tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#959 README.md: Update recommendation on Prometheus discovery
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#952 Add metric to show details of status condition of PVC resizing.
  docs/persistentvolumeclaim-metrics.md
  internal/store/persistentvolumeclaim.go
  internal/store/persistentvolumeclaim_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
