Repository kubernetes/kube-state-metrics, pull requests merged in 2019-04, with the labels that each got.

#708 kube_node_status_phase does not works. Updating Docs
  docs/node-metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#713 Add label for priority class in kube_pod_info #712
  docs/pod-metrics.md
  internal/collector/pod.go
  internal/collector/pod_test.go
  main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#709 internal/collector+pkg/metrics_store: Reduce allocation & improve hot path
  internal/collector/hpa.go
  internal/collector/job.go
  internal/collector/node.go
  internal/collector/persistentvolume.go
  internal/collector/persistentvolumeclaim.go
  internal/collector/pod.go
  internal/collector/pod_test.go
  internal/collector/replicaset.go
  internal/collector/service.go
  internal/collector/testutils.go
  internal/collector/utils.go
  pkg/metric/family.go
  pkg/metric/generator.go
  pkg/metric/metric.go
  pkg/metric/metric_test.go
  pkg/metrics_store/metrics_store.go
  pkg/metrics_store/metrics_store_test.go
  tests/lib/lib_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#711 README.md: Update compatibility matrix for kube-state-metrics v1.6
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#715 docs: minor improvements in kube-state-metrics README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#702 *: Cut v1.6.0-rc.0
  CHANGELOG.md
  VERSION
Labels: approved, cncf-cla: yes, lgtm, size/S

#716 Merge master into release-1.6 for v1.6.0-rc.0
  CHANGELOG.md
  README.md
  VERSION
Labels: approved, cncf-cla: yes, lgtm, size/S

#717 Add list/watch access to ClusterRole for CSR collector
  kubernetes/kube-state-metrics-cluster-role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#718 Add list/watch access to ClusterRole for CSR collector
  kubernetes/kube-state-metrics-cluster-role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#721 use a more idiomatic way of handling error messages
  go.mod
  go.sum
  internal/collector/cronjob.go
  internal/collector/testutils.go
  main.go
  pkg/options/types.go
  vendor/github.com/pkg/errors/.gitignore
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/appveyor.yml
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/stack.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XL

#722 use xenial dist in travis ci
  .travis.yml
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#720 fix: change the expectedType of the kube-client reflector to match the listWatch
  internal/collector/builder.go
  internal/collector/daemonset.go
  internal/collector/daemonset_test.go
  internal/collector/statefulset.go
  internal/collector/statefulset_test.go
  tests/manifests/daemonset.yaml
  tests/manifests/statefulset.yaml
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#723 PR #720 into master
  internal/collector/builder.go
  internal/collector/daemonset.go
  internal/collector/daemonset_test.go
  internal/collector/statefulset.go
  internal/collector/statefulset_test.go
  tests/manifests/daemonset.yaml
  tests/manifests/statefulset.yaml
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#728 Adding unit test and fixing typo
  pkg/options/types.go
  pkg/options/types_test.go
  pkg/whiteblacklist/whiteblacklist_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#729 *: Cut v1.6.0-rc.1
  CHANGELOG.md
  VERSION
Labels: approved, cncf-cla: yes, lgtm, size/XS

#732 Adding unit test
  internal/collector/utils_test.go
  pkg/options/types_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#724 bump versions of prometheus,kubernetes, and addon-resizer
  .travis.yml
  go.mod
  go.sum
  internal/collector/cronjob.go
  internal/collector/testutils.go
  kubernetes/kube-state-metrics-deployment.yaml
  main.go
  pkg/options/types.go
  tests/e2e.sh
  vendor/github.com/pkg/errors/.gitignore
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/appveyor.yml
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/stack.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XL

#733 *: Cut v1.6.0-rc.2
  CHANGELOG.md
  VERSION
Labels: approved, cncf-cla: yes, lgtm, size/XS

#734 Adding unit test
  internal/collector/testutils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#735 Do not run as root by default in Docker
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS
