Repository kubernetes/kube-state-metrics, pull requests merged in 2019-01, with the labels that each got.

#630 Remove the mentioning of `ksm_scrape_error_total` and `ksm_resources_per_scrape` metrics
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#629 Cut 1.5.0
  CHANGELOG.md
  README.md
  kubernetes/kube-state-metrics-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#631 Remove the obsolete metrics code
  main.go
  pkg/collectors/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#634 OWNERS: Add @mxinden
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#635 clarify the import location of Store interface in comments
  pkg/metrics_store/metrics_store.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#636 run gofmt -s on all of the source files
  main_test.go
  pkg/collectors/configmap.go
  pkg/collectors/cronjob.go
  pkg/collectors/daemonset.go
  pkg/collectors/deployment.go
  pkg/collectors/endpoint.go
  pkg/collectors/hpa.go
  pkg/collectors/job.go
  pkg/collectors/limitrange.go
  pkg/collectors/namespace.go
  pkg/collectors/node.go
  pkg/collectors/persistentvolume.go
  pkg/collectors/persistentvolumeclaim.go
  pkg/collectors/pod.go
  pkg/collectors/pod_test.go
  pkg/collectors/poddisruptionbudget.go
  pkg/collectors/replicaset.go
  pkg/collectors/replicationcontroller.go
  pkg/collectors/resourcequota.go
  pkg/collectors/secret.go
  pkg/collectors/service.go
  pkg/collectors/service_test.go
  pkg/collectors/statefulset.go
  pkg/collectors/utils.go
  pkg/whiteblacklist/whiteblacklist_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#637 tests: Add check-license script
  .travis.yml
  Makefile
  pkg/metrics/metrics_test.go
  pkg/metrics_store/metrics_store.go
  pkg/metrics_store/metrics_store_test.go
  pkg/whiteblacklist/whiteblacklist.go
  pkg/whiteblacklist/whiteblacklist_test.go
  tests/check_license.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#638 Add replicaset label metrics
  Documentation/replicaset-metrics.md
  pkg/collectors/replicaset.go
  pkg/collectors/replicaset_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#641 use the latest patch release of go 1.11
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#633 Deduplicate metric name
  internal/collector/configmap.go
  internal/collector/cronjob.go
  internal/collector/daemonset.go
  internal/collector/deployment.go
  internal/collector/endpoint.go
  internal/collector/hpa.go
  internal/collector/job.go
  internal/collector/limitrange.go
  internal/collector/namespace.go
  internal/collector/node.go
  internal/collector/persistentvolume.go
  internal/collector/persistentvolumeclaim.go
  internal/collector/pod.go
  internal/collector/poddisruptionbudget.go
  internal/collector/replicaset.go
  internal/collector/replicationcontroller.go
  internal/collector/resourcequota.go
  internal/collector/secret.go
  internal/collector/service.go
  internal/collector/statefulset.go
  pkg/metric/family.go
  pkg/metric/generator.go
  pkg/metric/metric.go
  pkg/metric/metric_test.go
  tests/lib/lib_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#643 tests: Add benchmark compare script and include in CI
  .travis.yml
  Makefile
  pkg/metric/metric_test.go
  tests/compare_benchmarks.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#646 Get GCP email account from gcloud's 'value' format
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#647 Remove accidentally committed file
  internal/collector/filename
Labels: approved, cncf-cla: yes, lgtm, size/XS

#648 Makefile: Add local build target
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS
