Repository kubernetes/kube-state-metrics, pull requests merged in 2019-06, with the labels that each got.

#779 kube-state-metrics-deployment: add k8s-app label
  kubernetes/kube-state-metrics-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#782 .travis.yml: Add job names
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#777 Add Metrics About StorageClass
  docs/README.md
  docs/storageclass-metrics.md
  internal/collector/builder.go
  internal/collector/storageclass.go
  internal/collector/storageclass_test.go
  kubernetes/kube-state-metrics-cluster-role.yaml
  pkg/options/collector.go
  tests/manifests/storageclass.yaml
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#783 Run check in CI for generated docs
  CONTRIBUTING.md
  Makefile
  docs/cli-arguments.md
  docs/horizontalpodautoscaler-metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#785 Makefile: Enable benchmarking against master
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#784 main_test.go: Fair benchmark
  main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#792 updating version for CI tools to latest stable versions. Fix #790
  Makefile
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#793 builder/main: allow collectors not enabled by default
  go.sum
  internal/store/builder.go
  main.go
  pkg/options/types.go
  pkg/options/types_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#773 feat: implement black/white- listing of metrics by regex
  docs/cli-arguments.md
  main.go
  pkg/options/options.go
  pkg/whiteblacklist/whiteblacklist.go
  pkg/whiteblacklist/whiteblacklist_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#797 Fixes Wrong description about metrics-server in README.md #794
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#791 store: add metrics for VerticalPodAutoscaler objects
  docs/README.md
  docs/verticalpodautoscaler-metrics.md
  go.mod
  go.sum
  internal/store/builder.go
  internal/store/verticalpodautoscaler.go
  internal/store/verticalpodautoscaler_test.go
  kubernetes/kube-state-metrics-cluster-role.yaml
  main.go
  tests/e2e.sh
  vendor/k8s.io/autoscaler/LICENSE
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/doc.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/register.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/zz_generated.deepcopy.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta1/doc.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta1/register.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta1/types.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/doc.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/register.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/types.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/zz_generated.deepcopy.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/poc.autoscaling.k8s.io/v1alpha1/doc.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/poc.autoscaling.k8s.io/v1alpha1/register.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/poc.autoscaling.k8s.io/v1alpha1/types.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/poc.autoscaling.k8s.io/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/clientset.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/doc.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/scheme/doc.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/scheme/register.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/autoscaling.k8s.io/v1/autoscaling.k8s.io_client.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/autoscaling.k8s.io/v1/doc.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/autoscaling.k8s.io/v1/generated_expansion.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/autoscaling.k8s.io/v1/verticalpodautoscaler.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/autoscaling.k8s.io/v1/verticalpodautoscalercheckpoint.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/autoscaling.k8s.io/v1beta1/autoscaling.k8s.io_client.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/autoscaling.k8s.io/v1beta1/doc.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/autoscaling.k8s.io/v1beta1/generated_expansion.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/autoscaling.k8s.io/v1beta1/verticalpodautoscaler.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/autoscaling.k8s.io/v1beta1/verticalpodautoscalercheckpoint.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/autoscaling.k8s.io/v1beta2/autoscaling.k8s.io_client.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/autoscaling.k8s.io/v1beta2/doc.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/autoscaling.k8s.io/v1beta2/generated_expansion.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/autoscaling.k8s.io/v1beta2/verticalpodautoscaler.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/autoscaling.k8s.io/v1beta2/verticalpodautoscalercheckpoint.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/poc.autoscaling.k8s.io/v1alpha1/doc.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/poc.autoscaling.k8s.io/v1alpha1/generated_expansion.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/poc.autoscaling.k8s.io/v1alpha1/poc.autoscaling.k8s.io_client.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/poc.autoscaling.k8s.io/v1alpha1/verticalpodautoscaler.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/poc.autoscaling.k8s.io/v1alpha1/verticalpodautoscalercheckpoint.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#799 add missing godoc comment for the WhiteBlackList.Parse method
  pkg/whiteblacklist/whiteblacklist.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#803 Update compatibility matrix to record only 5 kubernetes releases
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#804 use appsv1 apigroup for ReplicaSet
  internal/store/replicaset.go
  internal/store/replicaset_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#805 *: Cleanup references to removed API
  internal/store/hpa_test.go
  kubernetes/kube-state-metrics-deployment.yaml
  tests/manifests/hpa.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#807 fix go vet issues in whitblacklist.go
  pkg/whiteblacklist/whiteblacklist.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#808 rename kubeAnnotationsToPrometheusAnnotations to kubeAnnotationsToPrometheusLabels
  internal/store/certificatesigningrequest.go
  internal/store/configmap.go
  internal/store/cronjob.go
  internal/store/daemonset.go
  internal/store/deployment.go
  internal/store/endpoint.go
  internal/store/hpa.go
  internal/store/ingress.go
  internal/store/job.go
  internal/store/limitrange.go
  internal/store/namespace.go
  internal/store/node.go
  internal/store/persistentvolume.go
  internal/store/persistentvolumeclaim.go
  internal/store/poddisruptionbudget.go
  internal/store/replicaset.go
  internal/store/replicationcontroller.go
  internal/store/resourcequota.go
  internal/store/secret.go
  internal/store/service.go
  internal/store/statefulset.go
  internal/store/utils.go
  internal/store/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
