Repository kubernetes/kube-state-metrics, pull requests merged in 2020-06, with the labels that each got.

#1151 invalid url
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1155 cloudbuild.yaml: Add builds for k8s.gcr.io
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1152 *: merge release-1.9.7 to master
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1156 Avoid conflicts when mapping Kubernetes labels to Prometheus labels
  README.md
  internal/store/utils.go
  internal/store/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
