Repository kubernetes/kube-state-metrics, pull requests merged in 2020-01, with the labels that each got.

#1016 Update golangci-lint version to v1.22.2 (latest)
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1019 internal/store/hpa: Fix segfault in hpa metrics
  internal/store/hpa.go
  internal/store/hpa_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1021 *: Cut 1.9.1 release
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1022 *: Sync master branch with release-1.9 branch
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
  internal/store/hpa.go
  internal/store/hpa_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1023 internal/store/hpa.go: Fix segfault with External metrics
  internal/store/hpa.go
  internal/store/hpa_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1025 *: Cut v1.9.2 release
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1026 *: Sync master with release-1.9 branch
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
  internal/store/hpa.go
  internal/store/hpa_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1030 internal/store/: Remove hpa metric kube_hpa_status_current_metrics_av…
  docs/horizontalpodautoscaler-metrics.md
  internal/store/hpa.go
  internal/store/hpa_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1033 *: Cut v1.9.3 release
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1034 Add security context to deployment and statefulset
  examples/autosharding/statefulset.yaml
  examples/standard/deployment.yaml
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1035 Merge 1.9.3 back into master
  CHANGELOG.md
  README.md
  VERSION
  docs/horizontalpodautoscaler-metrics.md
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
  internal/store/hpa.go
  internal/store/hpa_test.go
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
Labels: approved, cncf-cla: yes, lgtm, size/L

#1038 Add lease collector
  docs/README.md
  docs/cli-arguments.md
  docs/lease-metrics.md
  examples/autosharding/cluster-role.yaml
  examples/standard/cluster-role.yaml
  internal/store/builder.go
  internal/store/lease.go
  internal/store/lease_test.go
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
  pkg/options/collector.go
  tests/manifests/lease.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1005 v2: change metrics port to 8080, telemetry port to 8081
  README.md
  docs/cli-arguments.md
  pkg/options/options.go
Labels: approved, cncf-cla: yes, lgtm, size/S, v2
