Repository kubernetes/kube-state-metrics, pull requests merged in 2020-07, with the labels that each got.

#1165 internal/store: convert k8s labels to snake case
  internal/store/utils.go
  internal/store/utils_test.go
  internal/store/volumeattachment_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1161 [release 1.9] cloudbuild.yaml: Add builds for k8s.gcr.io
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1171 Build binary fully in container build
  .dockerignore
  Dockerfile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#1172 add internal_ip to node_info
  docs/node-metrics.md
  internal/store/node.go
  internal/store/node_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1173 Dockerfile,Makefile: Fix building for k8s.gcr.io images
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1174 Makefile: Set default registry name to gcr.io/k8s-staging-kube-state-…
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1168 Rework resource metrics
  docs/pod-metrics.md
  internal/store/pod.go
  internal/store/pod_test.go
  main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1177 Backport Container Build Changes to Release 1.9
  .dockerignore
  .travis.yml
  Dockerfile
  Makefile
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1178 Add observedGeneration metric for DaemonSets
  docs/daemonset-metrics.md
  internal/store/daemonset.go
  internal/store/daemonset_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1181 Update DaemonSet updated_number_scheduled metric name to be consistent
  docs/daemonset-metrics.md
  internal/store/daemonset.go
  internal/store/daemonset_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1183 Adds new pod metric kube_pod_container_state_started
  docs/pod-metrics.md
  internal/store/pod.go
  internal/store/pod_test.go
  main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1188 Makefile: Bump golangci-lint to 1.29.0
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1186 Add repo SECURITY.md
  SECURITY.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1192 fix typos
  internal/store/builder.go
  pkg/builder/builder.go
  pkg/metric/family.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1190 Makefile: Push a single multi-arch image
  Makefile
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1193 Makefile: Enable experimental Docker CLI
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS
