Repository kubernetes/kube-state-metrics, pull requests merged in 2020-10, with the labels that each got.

#1235 add iscsi initiator name to persistentvolume_info
  docs/persistentvolume-metrics.md
  internal/store/persistentvolume.go
  internal/store/persistentvolume_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1253 Cut v2.0.0.-alpha.1
  CHANGELOG.md
  README.md
  VERSION
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1256 Fix test due to map iteration
  pkg/allow/allow_labels.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1255 fix typo in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1214 Added the job failure reason in kube_job_status_failed metric
  docs/job-metrics.md
  internal/store/job.go
  internal/store/job_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1262 Makefile: Override Commit in cloudbuild
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1261 Update to golang-1.15.3
  .github/workflows/ci.yml
  Dockerfile
  Makefile
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S

#1260 Migrate ingress and certificates away from deprecated APIs
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role.yaml
  internal/store/builder.go
  internal/store/certificatesigningrequest.go
  internal/store/certificatesigningrequest_test.go
  internal/store/ingress.go
  internal/store/ingress_test.go
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
  tests/manifests/csr.yaml
  tests/manifests/ingress.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1265 fix html tag in service-metrics.md
  docs/service-metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1266 Fix go version in go.mod
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1244 feat(persistentvolume): claimRef info to labels
  docs/persistentvolume-metrics.md
  internal/store/persistentvolume.go
  internal/store/persistentvolume_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1268 fix namespace parameter in README.md #1267
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1264 Makefile: Set tag via cloudbuild
  Makefile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1275 Remove ksonnet and move to absolute import paths
  examples/autosharding/statefulset.yaml
  jsonnet/kube-state-metrics/jsonnetfile.json
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
  scripts/jsonnetfile.json
  scripts/jsonnetfile.lock.json
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1278 Revert "Rework resource metrics"
  docs/pod-metrics.md
  internal/store/pod.go
  internal/store/pod_test.go
  main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1276 pod: add gauge for runtimeclass handler
  docs/pod-metrics.md
  internal/store/pod.go
  internal/store/pod_test.go
  main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1282 .github/: Update issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1284 Cut v2.0.0-alpha.2
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1285 Merge master into release-2.0 branch
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/ci.yml
  CHANGELOG.md
  Dockerfile
  Makefile
  README.md
  VERSION
  cloudbuild.yaml
  docs/job-metrics.md
  docs/persistentvolume-metrics.md
  docs/pod-metrics.md
  docs/service-metrics.md
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
  internal/store/builder.go
  internal/store/certificatesigningrequest.go
  internal/store/certificatesigningrequest_test.go
  internal/store/ingress.go
  internal/store/ingress_test.go
  internal/store/job.go
  internal/store/job_test.go
  internal/store/persistentvolume.go
  internal/store/persistentvolume_test.go
  internal/store/pod.go
  internal/store/pod_test.go
  jsonnet/kube-state-metrics/jsonnetfile.json
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
  main_test.go
  pkg/allow/allow_labels.go
  scripts/jsonnetfile.json
  scripts/jsonnetfile.lock.json
  tests/manifests/csr.yaml
  tests/manifests/ingress.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1290 README.md: Update section on container images
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1287 Fix pod-metric missing reasons
  docs/pod-metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1291 fix typo in node-metrics.md
  docs/node-metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1283 Fix some typos
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
