Repository kubernetes/kube-state-metrics, pull requests merged in 2020-09, with the labels that each got.

#1216 Label/Tags are shown in status tab
  docs/verticalpodautoscaler-metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1125 apply boundaries to metrics and allow via flag what labels to include
  docs/cli-arguments.md
  internal/store/builder.go
  internal/store/utils.go
  main.go
  main_test.go
  pkg/allow/allow_labels.go
  pkg/builder/types/interfaces.go
  pkg/metric_generator/generator.go
  pkg/metric_generator/generator_test.go
  pkg/options/options.go
  pkg/options/types.go
  pkg/options/types_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1217 Fix test as sometimes metrics keys and values are generated in differ…
  pkg/metric_generator/generator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1218 main.go: Add http request metric for kube-state-metrics main /metrics
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1231 Fix image names and clarify image promotion process
  README.md
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1233 Added Namespace to Rolebinding Jsonnet
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1234 e2e.sh: Update kind to 0.9.0
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1236 docs/pod-metrics.md: add missing condition label
  docs/job-metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1240 Reference closure scoped family generator
  main_test.go
  pkg/metric_generator/generator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
