Repository kubernetes/kube-state-metrics, pull requests merged in 2020-08, with the labels that each got.

#1195 migrate to KIND for e2e testing
  .travis.yml
  Makefile
  tests/README.md
  tests/e2e.sh
  tests/manifests/volumeattachment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1197 [Backport-1.9] Multi-Arch Images
  Makefile
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1196 revise OWNERS list
  OWNERS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1175 Update docs to point to new gcr registry
  README.md
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1180 Use run groups
  go.mod
  go.sum
  main.go
  vendor/github.com/oklog/run/.gitignore
  vendor/github.com/oklog/run/LICENSE
  vendor/github.com/oklog/run/README.md
  vendor/github.com/oklog/run/actors.go
  vendor/github.com/oklog/run/go.mod
  vendor/github.com/oklog/run/group.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#1160 Add DeprecatedVersion to struct FamilyGenerator and func NewFamilyGenerator
  internal/store/certificatesigningrequest.go
  internal/store/configmap.go
  internal/store/cronjob.go
  internal/store/daemonset.go
  internal/store/deployment.go
  internal/store/endpoint.go
  internal/store/horizontalpodautoscaler.go
  internal/store/ingress.go
  internal/store/job.go
  internal/store/lease.go
  internal/store/limitrange.go
  internal/store/mutatingwebhookconfiguration.go
  internal/store/namespace.go
  internal/store/networkpolicy.go
  internal/store/node.go
  internal/store/persistentvolume.go
  internal/store/persistentvolumeclaim.go
  internal/store/pod.go
  internal/store/poddisruptionbudget.go
  internal/store/replicaset.go
  internal/store/replicationcontroller.go
  internal/store/resourcequota.go
  internal/store/secret.go
  internal/store/service.go
  internal/store/statefulset.go
  internal/store/storageclass.go
  internal/store/validatingwebhookconfiguration.go
  internal/store/verticalpodautoscaler.go
  internal/store/volumeattachment.go
  pkg/metric_generator/generator.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1201 Build with same golang version as defined in Makefile
  Dockerfile
  Makefile
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1199 use github actions for CI checks
  .github/workflows/ci.yml
  .travis.yml
  Makefile
  README.md
  tests/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1202 jsonnet/mixin: adhere to monitoring mixins guidelines
  jsonnet/kube-state-metrics-mixin/alerts.libsonnet
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1203 Regenerate alerting rule examples
  examples/prometheus-alerting-rules/alerts.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1204 Fix generated alerts example
  examples/prometheus-alerting-rules/alerts.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1205 use yaml config friendly names for gh action checks
  .github/workflows/ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1206 rename gh action workflow and fix badge render
  .github/workflows/ci.yml
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1208 add fc/iscsi/nfs identifier tags to persistentvolume_info
  docs/persistentvolume-metrics.md
  internal/store/persistentvolume.go
  internal/store/persistentvolume_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
