Repository kubernetes/kube-state-metrics, pull requests merged in 2020-12, with the labels that each got.

#1322 Promote v2.0.0 to beta pre-release
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1323 Merge release-2.0 into master branch
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
  scripts/standard.jsonnet
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1304 Add "uid" label to every pod metric
  docs/pod-metrics.md
  internal/store/pod.go
  internal/store/pod_test.go
  main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1315 internal/store: fix high cyclo complexity
  .golangci.yml
  internal/store/node.go
  internal/store/pod.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1237 Host stable/kube-state-metrics helm chart
  .github/workflows/helm-cd.yaml
  .github/workflows/helm-ci.yaml
  charts/kube-state-metrics/.helmignore
  charts/kube-state-metrics/Chart.yaml
  charts/kube-state-metrics/LICENSE
  charts/kube-state-metrics/OWNERS
  charts/kube-state-metrics/README.md
  charts/kube-state-metrics/templates/NOTES.txt
  charts/kube-state-metrics/templates/_helpers.tpl
  charts/kube-state-metrics/templates/clusterrole.yaml
  charts/kube-state-metrics/templates/clusterrolebinding.yaml
  charts/kube-state-metrics/templates/deployment.yaml
  charts/kube-state-metrics/templates/kubeconfig-secret.yaml
  charts/kube-state-metrics/templates/pdb.yaml
  charts/kube-state-metrics/templates/podsecuritypolicy.yaml
  charts/kube-state-metrics/templates/psp-clusterrole.yaml
  charts/kube-state-metrics/templates/psp-clusterrolebinding.yaml
  charts/kube-state-metrics/templates/service.yaml
  charts/kube-state-metrics/templates/serviceaccount.yaml
  charts/kube-state-metrics/templates/servicemonitor.yaml
  charts/kube-state-metrics/templates/stsdiscovery-role.yaml
  charts/kube-state-metrics/templates/stsdiscovery-rolebinding.yaml
  charts/kube-state-metrics/values.yaml
  tests/ct.yaml
Labels: approved, cncf-cla: no, do-not-merge/invalid-commit-message, lgtm, size/XXL

#1327 Makefile: remove test-unit dependencies
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1326 helm chart: Fix GitHub action
  .github/workflows/helm-cd.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1329 Chart releaser name template and release
  .github/workflows/helm-cd.yaml
  charts/kube-state-metrics/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1334 Retry releasing chart after gh-pages branch protection was removed
  charts/kube-state-metrics/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
