Repository kubernetes/kube-state-metrics, pull requests merged in 2020-03, with the labels that each got.

#1085 Update README: revert to --resources and mention v2
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1088 Update README with a note about current cluster state
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1082 [e2e] Check labels documentation
  Makefile
  docs/README.md
  docs/deployment-metrics.md
  docs/horizontalpodautoscaler-metrics.md
  docs/mutatingwebhookconfiguration-metrics.md
  docs/namespace-metrics.md
  docs/node-metrics.md
  docs/pod-metrics.md
  docs/replicaset-metrics.md
  docs/validatingwebhookconfiguration-metrics.md
  go.mod
  tests/e2e/main_test.go
  tests/manifests/lease.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1092 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1097 [e2e] Remove redundant bash test + upgrade Minikube
  .travis.yml
  tests/README.md
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1098 v2: Renamed --namespace flag to --namespaces
  docs/cli-arguments.md
  pkg/options/options.go
  pkg/options/options_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1094 [e2e] Check errors in kube-state-metrics own metrics
  .gitignore
  go.mod
  tests/e2e.sh
  tests/e2e/README.md
  tests/e2e/framework.go
  tests/e2e/framework/framework.go
  tests/e2e/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1100 add kube_pod_host_network
  docs/pod-metrics.md
  internal/store/pod.go
  internal/store/pod_test.go
  main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1104 Fix typo in ingress-metric documentation
  docs/ingress-metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1106 fix typo in statefulset metrics documentation
  docs/statefulset-metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1107 v2: Rename storage class labels reclaimPolicy to reclaim_policy and volumeBindingMode to volume_binding_mode
  docs/storageclass-metrics.md
  internal/store/storageclass.go
  internal/store/storageclass_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1112 Fix title in volumeattachment metrics documentation
  docs/volumeattachment-metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
