Repository kubernetes/kube-state-metrics, pull requests merged in 2021-11, with the labels that each got.

#1626 Prepare release v2.2.4
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#1627 Merge changes from v2.2.4 back to master
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#1603 feat: kustomization for all examples
  README.md
  examples/autosharding/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/S, approved

#1571 endpoints: export number of ports as new metric
  docs/endpoint-metrics.md
  internal/store/endpoint.go
  internal/store/endpoint_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#1629 Use the architecture specified in the Makefile for the Docker image and binary
  Dockerfile
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1617 [release-2.1] Backport #1610
  internal/store/builder.go
  pkg/builder/builder.go
  pkg/builder/builder_test.go
  pkg/builder/types/interfaces.go
Labels: cncf-cla: yes, lgtm, size/L

#1636 Bump golang and kubernetes versions
  Makefile
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/S, approved

#1637 .github: Extract golangci-lint version
  .github/workflows/ci.yml
  .golangci.yml
  internal/store/persistentvolume.go
  internal/store/persistentvolume_test.go
  pkg/util/proc/reaper.go
  tests/e2e/main_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1633 OWNERS: add dgrisonnet to approvers
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1634 Add fpetkovski to approvers
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1645 images: use k8s-staging-test-infra/gcb-docker-gcloud
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1646 images: fix invalid k8s-staging-test-infra/gcb-docker-gcloud tag
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved
