Repository kubernetes/kube-state-metrics, pull requests merged in 2021-06, with the labels that each got.

#1492 Merge release v2.1.0-rc.0 back to master
  CHANGELOG.md
  README.md
  VERSION
  docs/node-metrics.md
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1493 Go 1.16.5 and update dependencies
  Makefile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1494 Prep release 2.1
  README.md
  VERSION
  docs/node-metrics.md
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1496 Changelog.md: Add missing update for v2.1.0
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1514 Add `WithAllowLabels` to public `BuilderInterface`
  internal/store/builder.go
  pkg/builder/builder.go
  pkg/builder/types/interfaces.go
Labels: approved, cncf-cla: yes, lgtm, size/S
