Repository kubernetes/kube-state-metrics, pull requests merged in 2021-04, with the labels that each got.

#1440 [release-2.0] Use latest golang version to build/update dependencies
  Makefile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1442 Fix role.yaml for helm2 compatibility
  charts/kube-state-metrics/Chart.yaml
  charts/kube-state-metrics/templates/role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1445 Fix typo in pod-metrics docs
  docs/pod-metrics.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#1403 Add wildcard option to metric-labels-allowlist
  docs/cli-arguments.md
  internal/store/pod_test.go
  internal/store/testutils.go
  internal/store/utils.go
  pkg/options/options.go
  pkg/options/types.go
  pkg/options/types_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1450 tests/e2e.sh: Fix image names
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1449 Cut v2.0.0
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1453 Sync master with release-2.0 branch
  .github/workflows/ci.yml
  CHANGELOG.md
  Makefile
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
  go.mod
  go.sum
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1455 Fix builder.Builder WithMetrics signature
  pkg/builder/builder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1459 Backport #1455: Fix builder.Builder WithMetrics signature
  pkg/builder/builder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1447 Add resourceVersion to CronJob metrics
  docs/cronjob-metrics.md
  internal/store/cronjob.go
  internal/store/cronjob_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1463 Bump k8s dependencies to v0.21.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1457 e2e: Test against multiple versions of k8s at the same time
  .github/workflows/ci.yml
  README.md
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1448 charts: Mark chart as deprecated
  charts/kube-state-metrics/Chart.yaml
  charts/kube-state-metrics/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1458 Replace deprecated io/ioutil
  main_test.go
  tests/e2e/framework/framework.go
  tests/e2e/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1466 [helm] remove github actions for helm continuous deploys
  .github/workflows/helm-cd.yaml
  .github/workflows/helm-ci.yaml
  tests/ct.yaml
Labels: approved, cncf-cla: yes, size/M
