Repository kubernetes/kube-state-metrics, pull requests merged in 2021-01, with the labels that each got.

#1345 charts: point out that the repo isn't set up yet
  charts/kube-state-metrics/Chart.yaml
  charts/kube-state-metrics/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1332 Add build info metric
  Makefile
  README.md
  examples/prometheus-alerting-rules/alerts.yaml
  go.mod
  go.sum
  main.go
Labels: approved, cncf-cla: no, cncf-cla: yes, lgtm, size/L

#1347 Release chart to gh-pages
  charts/kube-state-metrics/Chart.yaml
  charts/kube-state-metrics/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1346 options: change default host from 0.0.0.0 to ::
  docs/cli-arguments.md
  pkg/options/options.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1335 Add gh-pages Readme
  README.md
Labels: cncf-cla: yes, lgtm, size/M

#1361 feat(persistentvolume) Add Azure Disk Name to kube_persistentvolume_info
  docs/persistentvolume-metrics.md
  internal/store/persistentvolume.go
  internal/store/persistentvolume_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1355 Fix a spacing issue in the Helm chart README file
  charts/kube-state-metrics/Chart.yaml
  charts/kube-state-metrics/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1354 feat: Add support for native TLS
  docs/cli-arguments.md
  examples/prometheus-alerting-rules/alerts.yaml
  go.mod
  go.sum
  main.go
  pkg/options/options.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1365 e2e.sh: Update to kind v0.10.0
  Makefile
  tests/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1325 add useExistingRole option - to support running in specific namespace…
  charts/kube-state-metrics/Chart.yaml
  charts/kube-state-metrics/templates/clusterrolebinding.yaml
  charts/kube-state-metrics/templates/role.yaml
  charts/kube-state-metrics/templates/rolebinding.yaml
  charts/kube-state-metrics/values.yaml
Labels: approved, cncf-cla: yes, helm, lgtm, size/L

#1369 Fix create role
  charts/kube-state-metrics/Chart.yaml
  charts/kube-state-metrics/templates/role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1364 added: support for providing extraArgs via helm to ksm
  charts/kube-state-metrics/Chart.yaml
  charts/kube-state-metrics/templates/deployment.yaml
  charts/kube-state-metrics/values.yaml
Labels: approved, cncf-cla: yes, helm, lgtm, size/S
