Repository kubernetes/kube-state-metrics, pull requests merged in 2021-07, with the labels that each got.

#1520 feat: add `signer_name` to CSR metrics
  docs/certificatessigningrequest-metrics.md
  internal/store/certificatesigningrequest.go
  internal/store/certificatesigningrequest_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1521 Add a cardinality question to the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1528 docs: Fix typo
  docs/README.md
  docs/certificatesigningrequest-metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1512 [doc] Improve compatibility matrix notes
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1516 [release-2.1] Backport #1514
  internal/store/builder.go
  pkg/builder/builder.go
  pkg/builder/types/interfaces.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1529 go.mod: Update and minimize dependencies
  examples/prometheus-alerting-rules/alerts.yaml
  go.mod
  go.sum
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1530 add mrueg to approvers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1531 use new promlint package and bump prometheus cli
  Makefile
  go.mod
  go.sum
  tests/e2e/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1499 Replace multiListerWatcher with independent listWatchers per namespace
  internal/store/builder.go
  main.go
  main_test.go
  pkg/builder/builder.go
  pkg/builder/types/interfaces.go
  pkg/listwatch/listwatch.go
  pkg/listwatch/namespace_denylist.go
  pkg/metrics_store/metrics_writer.go
  pkg/metrics_store/metrics_writer_test.go
  pkg/metricshandler/metrics_handler.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1537 Use BuilderInterface instead of internal/store.Builder in metricshandler
  pkg/metricshandler/metrics_handler.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1533 OWNERS: Add dgrisonnet and fpetkovski to reviewers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1540 Cherry pick for v2.1.1 / Cut Release
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/prometheus-alerting-rules/alerts.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
  go.mod
  go.sum
  internal/store/builder.go
  main.go
  main_test.go
  pkg/builder/builder.go
  pkg/builder/types/interfaces.go
  pkg/listwatch/listwatch.go
  pkg/listwatch/namespace_denylist.go
  pkg/metrics_store/metrics_writer.go
  pkg/metrics_store/metrics_writer_test.go
  pkg/metricshandler/metrics_handler.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1542 CHANGELOG: apply changes for v2.1.1
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1543 Merge 2.1.1 back to default branch
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1544 cloudbuild.yaml: Update cloudbuild image
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
