Repository kubernetes/kube-state-metrics, pull requests merged in 2021-08, with the labels that each got.

#1534 Add ReadyReplicas metric to deployment metric family
  docs/deployment-metrics.md
  internal/store/deployment.go
  internal/store/deployment_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1545 Support for kubernetes 1.22.0 / Update dependencies
  Makefile
  README.md
  go.mod
  go.sum
  tests/e2e.sh
Labels: cncf-cla: yes, lgtm, size/L, approved

#1532 Add statefulset availablereplicas metric
  docs/statefulset-metrics.md
  internal/store/statefulset.go
  internal/store/statefulset_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1535 Added additional attributes for Cronjob and Node entities : Fixes issue and #1509
  docs/cronjob-metrics.md
  docs/node-metrics.md
  internal/store/cronjob.go
  internal/store/cronjob_test.go
  internal/store/node.go
  internal/store/node_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#1519 capture start time for containers in terminated state
  internal/store/pod.go
  internal/store/pod_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1548 Add arg use-api-server-cache to set resourceVersion=0 for ListWatch
  docs/cli-arguments.md
  internal/store/builder.go
  main.go
  main_test.go
  pkg/builder/builder.go
  pkg/builder/types/interfaces.go
  pkg/options/options.go
  pkg/watch/watch.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#1550 *: Cut v2.2.0 release
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#1553 Merge release 2.2 back to default branch
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#1555 SECURITY_CONTACTS: Add myself as a contact
  SECURITY_CONTACTS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1556 Replace deprecated functions
  internal/store/deployment.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1560 go.mod: Bump dependencies, move to go-1.17
  .github/workflows/ci.yml
  Dockerfile
  Makefile
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved

#1565 internal: Migrate HPA API version to autoscaling/v2beta2
  internal/store/builder.go
  internal/store/horizontalpodautoscaler.go
  internal/store/horizontalpodautoscaler_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved
