Repository kubernetes/kube-state-metrics, pull requests merged in 2021-12, with the labels that each got.

#1643 Add the "--opt-in-metrics" argument to the CLI to allow for opt-in metrics
  docs/cli-arguments.md
  main.go
  pkg/metric_generator/generator.go
  pkg/optin/optin.go
  pkg/optin/optin_test.go
  pkg/options/options.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#1648 Add "kube_horizontalpodautoscaler_info" metric
  docs/horizontalpodautoscaler-metrics.md
  internal/store/horizontalpodautoscaler.go
  internal/store/horizontalpodautoscaler_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1649 Prepare 2.3.0
  CHANGELOG.md
  Makefile
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
  go.mod
  go.sum
  tests/e2e.sh
Labels: cncf-cla: yes, lgtm, size/L, approved

#1651 Update compatibility matrix
  README.md
Labels: cncf-cla: yes, lgtm, size/S, approved

#1652 Add ingressclass to kube_ingress_info metric
  docs/ingress-metrics.md
  internal/store/ingress.go
  internal/store/ingress_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1653 pdb: use plural form of resource name in allowlist key
  internal/store/builder.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1657 Release 2.3
  README.md
  internal/store/builder.go
Labels: cncf-cla: yes, lgtm, size/S, approved
