Repository kubernetes/kube-state-metrics, pull requests merged in 2022-06, with the labels that each got.

#1710 feat: enable customresource metrics by configuration
  docs/README.md
  docs/cli-arguments.md
  docs/customresourcestate-metrics.md
  go.mod
  go.sum
  main.go
  pkg/customresourcestate/config.go
  pkg/customresourcestate/config_test.go
  pkg/customresourcestate/doc.go
  pkg/customresourcestate/example_config.yaml
  pkg/customresourcestate/registry_factory.go
  pkg/customresourcestate/registry_factory_test.go
  pkg/options/options.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#1746 *: Cut 2.5.0 release
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#1748 Update release instructions
  RELEASE.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1747 Merge Release 2.5 back to master
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#1750 Switch registry from k8s.gcr.io to registry.k8s.io
  README.md
  examples/autosharding/statefulset.yaml
  examples/standard/deployment.yaml
  scripts/standard.jsonnet
  tests/e2e.sh
Labels: cncf-cla: yes, lgtm, size/S, approved

#1754 fix customresourcestate metric names to not contain underscores
  pkg/customresourcestate/config.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1760 Update kube_node_status_allocatable unit doc
  docs/node-metrics.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1761 add new kube_endpoint_address metric
  docs/endpoint-metrics.md
  internal/store/endpoint.go
  internal/store/endpoint_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1764 update the description about metrics server
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1766 To support read the timestamp fields of custom resources
  pkg/customresourcestate/registry_factory.go
  pkg/customresourcestate/registry_factory_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1774 Update the developer documentation for adding a new resource metric collector
  docs/developer/guide.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1773 Add support for the ServiceAccount resource (Ref: #1717)
  docs/README.md
  docs/cli-arguments.md
  docs/serviceaccount-metrics.md
  examples/autosharding/cluster-role.yaml
  examples/standard/cluster-role.yaml
  internal/store/builder.go
  internal/store/serviceaccount.go
  internal/store/serviceaccount_test.go
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
  pkg/options/resource.go
  tests/manifests/serviceaccount.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved
