Repository kubernetes/kube-state-metrics, pull requests merged in 2022-12, with the labels that each got.

#1910 Add Metrics for EndpointSlices
  docs/README.md
  docs/endpointslice-metrics.md
  examples/autosharding/cluster-role.yaml
  examples/standard/cluster-role.yaml
  internal/store/builder.go
  internal/store/endpointslice.go
  internal/store/endpointslice_test.go
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
  tests/e2e/main_test.go
  tests/manifests/endpointslice.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved

#1923 Empty string for "owner_*" dimensions in all metrics.
  docs/persistentvolumeclaim-metrics.md
  internal/store/job.go
  internal/store/job_test.go
  internal/store/lease.go
  internal/store/persistentvolumeclaim.go
  internal/store/persistentvolumeclaim_test.go
  internal/store/pod.go
  internal/store/pod_test.go
  internal/store/replicaset.go
  internal/store/replicaset_test.go
  internal/store/replicationcontroller.go
  internal/store/replicationcontroller_test.go
  pkg/app/server_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage

#1921 Remove duplicated MetricsWriter implementation
  internal/store/builder.go
  pkg/builder/builder.go
  pkg/builder/types/interfaces.go
  pkg/metrics_store/metrics_store.go
  pkg/metrics_store/metrics_store_test.go
  pkg/metrics_store/metrics_writer.go
  pkg/metrics_store/metrics_writer_test.go
  pkg/metricshandler/metrics_handler.go
  tests/lib/lib_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-triage

#1916 Add metrics for config file changes
  README.md
  internal/wrapper.go
  pkg/app/server.go
  pkg/options/options.go
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted

#1924 docs: add status badge for the periodic cronjob
  .github/workflows/govulncheck.yml
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, triage/accepted

#1931 Rename references from master to main branch
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/ci.yml
  Makefile
  README.md
  RELEASE.md
  docs/developer/guide.md
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage

#1933 Bump dependencies and linter
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
  README.md
  go.mod
  go.sum
  tests/e2e.sh
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-triage

#1930 Make CRS metrics type dynamic
  pkg/customresourcestate/custom_resource_metrics_test.go
  pkg/customresourcestate/registry_factory.go
  pkg/metric/metric.go
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted

#1936 Add develop doc on adding new metrics
  docs/developer/guide.md
  docs/statefulset-metrics.md
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-triage
