Repository kubernetes/kube-state-metrics, pull requests merged in 2022-11, with the labels that each got.

#1831 add ContainerResourceSourceType for hpa metrics
  internal/store/horizontalpodautoscaler.go
  internal/store/horizontalpodautoscaler_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#1849 Recommend kube-scheduler's metrics
  docs/pod-metrics.md
  internal/store/pod.go
  internal/store/pod_test.go
  pkg/app/server_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#1874 Bump dependencies
  Makefile
  go.mod
  go.sum
  tests/e2e.sh
Labels: cncf-cla: yes, lgtm, size/L, approved

#1866 add myself to OWNERs
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1878 Detect vulns actually used by KSM
  .github/workflows/cron.yml
Labels: cncf-cla: yes, lgtm, size/S, approved

#1823 Support filtering label allowlist by "*"
  docs/cli-arguments.md
  internal/store/builder.go
  internal/store/builder_test.go
  pkg/options/options.go
  pkg/options/types_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#1813 introduce custom-resources-only flag ...
  docs/cli-arguments.md
  pkg/app/server.go
  pkg/options/options.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1876 Add retention policy metrics for KEP-1847
  docs/statefulset-metrics.md
  internal/store/statefulset.go
  internal/store/statefulset_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#1888 go.mod: Bump exporter-toolkit to 0.8.1
  go.mod
  go.sum
  pkg/app/server.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1834 Incorporate Cobra
  docs/cli-arguments.md
  go.mod
  go.sum
  main.go
  pkg/options/autoload.go
  pkg/options/options.go
  pkg/options/options_test.go
  scripts/generate-help-text.sh
Labels: cncf-cla: yes, lgtm, size/L, approved

#1835 Deprecate VPA
  docs/verticalpodautoscaler-metrics.md
  internal/store/verticalpodautoscaler.go
  internal/store/verticalpodautoscaler_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1880 Allow labelFromKey field for all applicable types
  docs/customresourcestate-metrics.md
  pkg/customresourcestate/config_metrics_types.go
  pkg/customresourcestate/registry_factory.go
  pkg/customresourcestate/registry_factory_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#1890 Add node deletionTimestamp metric
  docs/node-metrics.md
  internal/store/node.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1827 Incorporate Viper
  docs/cli-arguments.md
  docs/node-metrics.md
  go.mod
  go.sum
  internal/wrapper.go
  main.go
  pkg/app/server.go
  pkg/options/options.go
  pkg/options/options_test.go
  tests/e2e.sh
  tests/e2e/hot-reload_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#1894 update kube_node_status_{capacity/allocatable} doc to clarify difference
  docs/node-metrics.md
Labels: cncf-cla: yes, lgtm, size/XS, kind/documentation, approved

#1900 Add rexagod as reviewer
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1906 Start using autoscaling/v2 for HorizontalPodAutoscaler
  internal/store/builder.go
  internal/store/horizontalpodautoscaler.go
  internal/store/horizontalpodautoscaler_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#1905 Add ingress class metrics
  docs/README.md
  docs/ingressclass-metrics.md
  examples/autosharding/cluster-role.yaml
  examples/standard/cluster-role.yaml
  internal/store/builder.go
  internal/store/ingressclass.go
  internal/store/ingressclass_test.go
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
  tests/e2e/main_test.go
  tests/manifests/ingress.yaml
  tests/manifests/ingressclass.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved

#1896 *: Cut v2.7.0
  CHANGELOG.md
  OWNERS
  README.md
  VERSION
  docs/README.md
  docs/cli-arguments.md
  docs/ingressclass-metrics.md
  docs/node-metrics.md
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
  go.mod
  go.sum
  internal/store/builder.go
  internal/store/horizontalpodautoscaler.go
  internal/store/horizontalpodautoscaler_test.go
  internal/store/ingressclass.go
  internal/store/ingressclass_test.go
  internal/store/node.go
  internal/wrapper.go
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
  main.go
  pkg/app/server.go
  pkg/options/options.go
  pkg/options/options_test.go
  tests/e2e.sh
  tests/e2e/hot-reload_test.go
  tests/e2e/main_test.go
  tests/manifests/ingress.yaml
  tests/manifests/ingressclass.yaml
Labels: cncf-cla: yes, lgtm, size/XL, approved

#1908 Merge Release 2.7 back to master branch
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved

#1914 Add CatherineF-dev as reviewer
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1918 Update github.com/prometheus/exporter-toolkit
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage
