Repository kubernetes/kube-state-metrics, pull requests merged in 2022-07, with the labels that each got.

#1759 Add support for role and cluster role
  docs/README.md
  docs/cli-arguments.md
  docs/clusterrole-metrics.md
  docs/role-metrics.md
  examples/autosharding/cluster-role.yaml
  examples/standard/cluster-role.yaml
  internal/store/builder.go
  internal/store/clusterrole.go
  internal/store/clusterrole_test.go
  internal/store/role.go
  internal/store/role_test.go
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
  pkg/options/resource.go
  tests/manifests/clusterole.yaml
  tests/manifests/role.yaml
Labels: cncf-cla: yes, lgtm, size/XL, approved

#1780 SECURITY_CONTACTS: Sync with OWNERS
  SECURITY_CONTACTS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1784 Fix custom resource metrics documentation
  docs/customresourcestate-metrics.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1788 [FEAT] expose current metric values
  docs/horizontalpodautoscaler-metrics.md
  internal/store/horizontalpodautoscaler.go
  internal/store/horizontalpodautoscaler_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved
