Repository kubernetes/kube-state-metrics, pull requests merged in 2022-10, with the labels that each got.

#1845 Allow Lease metrics to be exported across all namespaces
  docs/lease-metrics.md
  internal/store/lease.go
  internal/store/lease_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1819 Build with go 1.19 / update to k8s 1.25
  .github/workflows/ci.yml
  Dockerfile
  Makefile
  README.md
  go.mod
  go.sum
  pkg/util/proc/reaper_unsupported.go
  tools/tools.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#1844 Import k8s metrics stability framework
  go.mod
  go.sum
  internal/store/certificatesigningrequest.go
  internal/store/certificatesigningrequest_test.go
  internal/store/configmap.go
  internal/store/configmap_test.go
  internal/store/cronjob.go
  internal/store/cronjob_test.go
  internal/store/daemonset.go
  internal/store/daemonset_test.go
  internal/store/deployment.go
  internal/store/deployment_test.go
  internal/store/endpoint.go
  internal/store/endpoint_test.go
  internal/store/horizontalpodautoscaler.go
  internal/store/horizontalpodautoscaler_test.go
  internal/store/ingress.go
  internal/store/ingress_test.go
  internal/store/job.go
  internal/store/job_test.go
  internal/store/limitrange.go
  internal/store/limitrange_test.go
  internal/store/namespace.go
  internal/store/namespace_test.go
  internal/store/node.go
  internal/store/node_test.go
  internal/store/persistentvolume.go
  internal/store/persistentvolume_test.go
  internal/store/persistentvolumeclaim.go
  internal/store/persistentvolumeclaim_test.go
  internal/store/pod.go
  internal/store/pod_test.go
  internal/store/poddisruptionbudget.go
  internal/store/poddisruptionbudget_test.go
  internal/store/replicaset.go
  internal/store/replicaset_test.go
  internal/store/replicationcontroller.go
  internal/store/replicationcontroller_test.go
  internal/store/resourcequota.go
  internal/store/resourcequota_test.go
  internal/store/secret.go
  internal/store/secret_test.go
  internal/store/service.go
  internal/store/service_test.go
  internal/store/statefulset.go
  internal/store/statefulset_test.go
  internal/store/storageclass.go
  internal/store/storageclass_test.go
  pkg/app/server_test.go
  pkg/metric_generator/generator.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#1856 customresourcestate fix type indentation in example
  docs/customresourcestate-metrics.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1850 Represent GVK information as labels
  docs/customresourcestate-metrics.md
  pkg/customresourcestate/config.go
  pkg/customresourcestate/registry_factory.go
  pkg/customresourcestate/registry_factory_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1867 .github: Update actions
  .github/workflows/ci.yml
Labels: cncf-cla: yes, lgtm, size/M, approved

#1865 Harden and add gosec linter
  .golangci.yml
  internal/store/job.go
  internal/store/secret.go
  main.go
  pkg/app/server.go
  pkg/app/server_test.go
  pkg/builder/builder_test.go
  pkg/metrics_store/metrics_writer_test.go
  pkg/metricshandler/metrics_handler.go
  pkg/options/options.go
  tests/e2e/main_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1826 Handle singular labels in allowlist
  internal/store/builder.go
  pkg/app/server.go
  pkg/builder/types/interfaces.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1870 Fix typos in customresourcestate-metrics doc
  docs/customresourcestate-metrics.md
Labels: cncf-cla: yes, lgtm, size/XS, approved
