Repository kubernetes/kube-state-metrics, pull requests merged in 2022-03, with the labels that each got.

#1675 Adds kube_pod_nodeselector metric
  docs/README.md
  docs/pod-metrics.md
  internal/store/pod.go
  internal/store/pod_test.go
  pkg/app/server_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#1702 Prepare 2.4.2
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#1706 Assert that newlines in coma separated arguments are ignored
  pkg/options/types_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1699 Properly initialize KSM server test
  pkg/app/server_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1708 Update dependencies
  Makefile
  go.mod
  go.sum
  tests/e2e.sh
Labels: cncf-cla: yes, lgtm, size/M, approved
