Repository kubernetes/kube-state-metrics, pull requests merged in 2022-08, with the labels that each got.

#1725 feat(hpa): status current metric
  docs/horizontalpodautoscaler-metrics.md
  internal/store/horizontalpodautoscaler.go
  internal/store/horizontalpodautoscaler_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1808 Replace pkg/errors with stdlib errors
  go.mod
  internal/store/builder.go
  internal/store/cronjob.go
  internal/store/testutils.go
  pkg/allowdenylist/allowdenylist.go
  pkg/app/server.go
  pkg/metricshandler/metrics_handler.go
  tests/e2e/framework/framework.go
  tests/e2e/main_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1807 feat(logging): migration to structure logging for main.go, pkg/ & internal/ folders
  internal/store/builder.go
  main.go
  pkg/app/server.go
  pkg/customresourcestate/registry_factory.go
  pkg/metricshandler/metrics_handler.go
  pkg/options/types.go
  pkg/util/proc/reaper.go
Labels: cncf-cla: yes, lgtm, size/M, approved, priority/important-longterm, kind/cleanup, wg/structured-logging

#1777 pkg/customresourcestate implement info and stateSet metric type and refactor configuration file
  docs/customresourcestate-metrics.md
  pkg/customresourcestate/config.go
  pkg/customresourcestate/config_metrics_types.go
  pkg/customresourcestate/config_test.go
  pkg/customresourcestate/custom_resource_metrics.go
  pkg/customresourcestate/example_config.yaml
  pkg/customresourcestate/registry_factory.go
  pkg/customresourcestate/registry_factory_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#1799 Add support for rolebindings
  docs/README.md
  docs/cli-arguments.md
  docs/clusterrolebinding-metrics.md
  docs/rolebinding-metrics.md
  examples/autosharding/cluster-role.yaml
  examples/standard/cluster-role.yaml
  internal/store/builder.go
  internal/store/clusterrolebinding.go
  internal/store/clusterrolebinding_test.go
  internal/store/rolebinding.go
  internal/store/rolebinding_test.go
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
  pkg/options/resource.go
  tests/manifests/clusterrolebinding.yaml
  tests/manifests/rolebinding.yaml
Labels: cncf-cla: yes, lgtm, size/XL, approved

#1809 Do not expose info metric for nil objects
  pkg/customresourcestate/registry_factory.go
  pkg/customresourcestate/registry_factory_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1812 graduate new endpoint metrics to STABLE
  docs/endpoint-metrics.md
  internal/store/endpoint.go
  internal/store/endpoint_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1789 Update dependencies
  .github/workflows/ci.yml
  Makefile
  cloudbuild.yaml
  docs/cli-arguments.md
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved

#1810 Prevent definition of same gvk in custom resource configuration
  docs/customresourcestate-metrics.md
  pkg/customresourcestate/config.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1816 Remove RBAC resources from default exposed metric set
  docs/README.md
  docs/cli-arguments.md
  pkg/options/resource.go
  tests/e2e/main_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1814 feat: Add local storage labels to kube_persistentvolume_info
  docs/persistentvolume-metrics.md
  internal/store/persistentvolume.go
  internal/store/persistentvolume_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#1817 *: Cut v2.6.0
  CHANGELOG.md
  README.md
  VERSION
  docs/persistentvolume-metrics.md
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
  internal/store/persistentvolume.go
  internal/store/persistentvolume_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#1818 Merge Release 2.6.0 back to master
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#1821 Promote two metrics kube_pod_container_status_waiting_reason and kube_deployment_status_replicas_ready to stable
  docs/deployment-metrics.md
  docs/pod-metrics.md
Labels: cncf-cla: yes, lgtm, size/XS, approved
