Repository kubernetes/kube-state-metrics, pull requests merged in 2022-02, with the labels that each got.

#1674 jsonnet: Drop all Linux capabilities
  examples/autosharding/statefulset.yaml
  examples/standard/deployment.yaml
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1677 tools: Switch from benchcmp to benchstat
  go.mod
  go.sum
  tests/compare_benchmarks.sh
  tools/tools.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1681 Bump go to 1.17.6 and dependencies
  Makefile
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved

#1682 Makefile: Use go 1.17.7
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1683 Prepare release 2.4
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#1692 Increase build timeout to 1800s
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1693 Increase build timeout to 1800s
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1694 Bump patch version
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#1687 Add default label of uid for service
  docs/service-metrics.md
  internal/store/service.go
  internal/store/service_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved
