Repository kubernetes/kube-state-metrics, pull requests merged in 2022-09, with the labels that each got.

#1822 GitHub Workflows security hardening
  .github/workflows/ci.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1752 add exit code
  docs/pod-metrics.md
  internal/store/pod.go
  internal/store/pod_test.go
  pkg/app/server_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1838 fix/docs: Typo correction in SA metrics
  docs/serviceaccount-metrics.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1841 Do not expose ingress path metric when service is nil
  internal/store/ingress.go
  internal/store/ingress_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved
