Repository kubernetes/kube-state-metrics, pull requests merged in 2022-05, with the labels that each got.

#1726 Update go 1.18 / update dependencies
  .github/workflows/ci.yml
  Dockerfile
  Makefile
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved

#1731 internal/store: fix metrics slice length
  internal/store/pod.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1727 feat: Add CSI support to PV Metrics
  docs/persistentvolume-metrics.md
  internal/store/persistentvolume.go
  internal/store/persistentvolume_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1732 Add missing LastSuccessfulTime metric
  docs/cronjob-metrics.md
  internal/store/cronjob.go
  internal/store/cronjob_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#1742 .github/workflows: Update golangci-lint to v1.46.2
  .github/workflows/ci.yml
Labels: cncf-cla: yes, lgtm, approved

#1743 Bump to go 1.18.2, k8s 1.24, kind 0.14.0, prometheus 2.35.0
  Makefile
  go.mod
  go.sum
  tests/e2e.sh
Labels: cncf-cla: yes, lgtm, size/L, approved

#1734 internal/store: fix metrics slice length for init containers
  internal/store/pod.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1741 Adding Unix creationTimestamp to PV/PVC metrics
  docs/persistentvolume-metrics.md
  docs/persistentvolumeclaim-metrics.md
  internal/store/persistentvolume.go
  internal/store/persistentvolume_test.go
  internal/store/persistentvolumeclaim.go
  internal/store/persistentvolumeclaim_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved
