Repository kubernetes/kube-state-metrics, pull requests merged in 2023-04, with the labels that each got.

#2046 Fix casing while scraping failure reason for `kube_job_status_failed`
  internal/store/job.go
  internal/store/job_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage

#2004 Adhere to OTel-Prometheus standard for labels
  go.mod
  go.sum
  internal/store/node.go
  internal/store/pod.go
  internal/store/utils.go
  pkg/customresourcestate/registry_factory.go
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#2048 2047: Add LabelsFromPath functionality to Info metrics
  pkg/customresourcestate/registry_factory.go
  pkg/customresourcestate/registry_factory_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage
