Repository kubernetes/kube-state-metrics, pull requests merged in 2023-06, with the labels that each got.

#2089 Fix cyclomatic complexity in KSM files
  internal/store/horizontalpodautoscaler.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, needs-triage

#1990 feat: Enable semantic commit messages
  .github/workflows/semantic.yml
  CONTRIBUTING.md
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted

#2101 docs: update multi-arch version to v2.9.2 in README.md
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage

#2106 docs: Document RBAC and remove outdated info
  docs/customresourcestate-metrics.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage
