Repository kubernetes/kube-state-metrics, pull requests merged in 2023-08, with the labels that each got.

#2128 chore: Add dependabot config
  .github/dependabot.yml
Labels: cncf-cla: yes, lgtm, size/S, approved, triage/accepted

#2134 feat: add volumemode to PVC info metric
  docs/persistentvolumeclaim-metrics.md
  internal/store/persistentvolumeclaim.go
  internal/store/persistentvolumeclaim_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted

#2157 fix: custommetrics: log no _info suffix in name only once per reading the configuration
  pkg/customresourcestate/registry_factory.go
  pkg/metric_generator/generator.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, triage/accepted

#2151 docs: Add example for non map Arrays
  docs/customresourcestate-metrics.md
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted

#2163 fix(customresourcestate): typo in Error message
  pkg/customresourcestate/registry_factory.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage

#2148 feat: implement kube_pod_status_initialized_time
  docs/pod-metrics.md
  internal/store/pod.go
  internal/store/pod_test.go
  pkg/app/server_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage

#2145 feat: disable labels and annotations metrics when metric-annotations-…
  internal/store/certificatesigningrequest.go
  internal/store/certificatesigningrequest_test.go
  internal/store/clusterrole.go
  internal/store/clusterrolebinding.go
  internal/store/configmap.go
  internal/store/cronjob.go
  internal/store/cronjob_test.go
  internal/store/daemonset.go
  internal/store/daemonset_test.go
  internal/store/deployment.go
  internal/store/deployment_test.go
  internal/store/endpoint.go
  internal/store/endpoint_test.go
  internal/store/endpointslice.go
  internal/store/endpointslice_test.go
  internal/store/horizontalpodautoscaler.go
  internal/store/horizontalpodautoscaler_test.go
  internal/store/ingress.go
  internal/store/ingress_test.go
  internal/store/ingressclass.go
  internal/store/ingressclass_test.go
  internal/store/job.go
  internal/store/job_test.go
  internal/store/namespace.go
  internal/store/namespace_test.go
  internal/store/networkpolicy.go
  internal/store/networkpolicy_test.go
  internal/store/node.go
  internal/store/node_test.go
  internal/store/persistentvolume.go
  internal/store/persistentvolume_test.go
  internal/store/persistentvolumeclaim.go
  internal/store/persistentvolumeclaim_test.go
  internal/store/pod.go
  internal/store/pod_test.go
  internal/store/poddisruptionbudget.go
  internal/store/poddisruptionbudget_test.go
  internal/store/replicaset.go
  internal/store/replicaset_test.go
  internal/store/role.go
  internal/store/rolebinding.go
  internal/store/secret.go
  internal/store/secret_test.go
  internal/store/service.go
  internal/store/service_test.go
  internal/store/serviceaccount.go
  internal/store/statefulset.go
  internal/store/statefulset_test.go
  internal/store/storageclass.go
  internal/store/storageclass_test.go
  pkg/app/server_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-triage

#2164 docs: Update labels and annotations allowlist
  docs/cli-arguments.md
  pkg/options/options.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage

#2166 fix: Index out of range in metrics_store.SanitizeHeaders
  pkg/metrics_store/metrics_writer.go
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-triage

#2168 build: Bump dependencies
  .github/workflows/ci.yml
  Makefile
  go.mod
  go.sum
  internal/store/cronjob.go
  internal/store/ingress.go
  internal/store/ingressclass.go
  internal/store/persistentvolume_test.go
  internal/store/serviceaccount_test.go
  pkg/customresourcestate/custom_resource_metrics_test.go
  pkg/customresourcestate/registry_factory_test.go
  pkg/options/types_test.go
  tests/e2e.sh
  tools/go.mod
  tools/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage

#2154 fix: custommetrics: always extract the headers but only write it when we have metrics
  internal/store/builder.go
  pkg/metrics_store/metrics_writer.go
  pkg/metrics_store/metrics_writer_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#2067 feat: allow field KV general matching
  docs/customresourcestate-metrics.md
  pkg/customresourcestate/registry_factory.go
  pkg/customresourcestate/registry_factory_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved, triage/accepted

#2144 feat: hot reload kubeconfig
  internal/wrapper.go
  tests/e2e.sh
  tests/e2e/hot-reload-kubeconfig_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#2090 feat: Add support for endpoint topology routing hints
  docs/endpointslice-metrics.md
  internal/store/endpointslice.go
  internal/store/endpointslice_test.go
Labels: cncf-cla: yes, size/M, approved, triage/accepted

#2176 chore: Cut v2.10.0
  CHANGELOG.md
  README.md
  VERSION
  docs/endpointslice-metrics.md
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/daemonsetsharding/cluster-role-binding.yaml
  examples/daemonsetsharding/cluster-role.yaml
  examples/daemonsetsharding/daemonset-service.yaml
  examples/daemonsetsharding/daemonset.yaml
  examples/daemonsetsharding/deployment-service.yaml
  examples/daemonsetsharding/deployment.yaml
  examples/daemonsetsharding/service-account.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
  internal/store/endpointslice.go
  internal/store/endpointslice_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-triage

#2181 chore: Merge Release 2.10 back to main
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/daemonsetsharding/cluster-role-binding.yaml
  examples/daemonsetsharding/cluster-role.yaml
  examples/daemonsetsharding/daemonset-service.yaml
  examples/daemonsetsharding/daemonset.yaml
  examples/daemonsetsharding/deployment-service.yaml
  examples/daemonsetsharding/deployment.yaml
  examples/daemonsetsharding/service-account.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage
