Repository kubernetes/kube-state-metrics, pull requests merged in 2023-11, with the labels that each got.

#2214 chore: Restructure `release-2.10` for `v2.10.1`
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/ci.yml
  .github/workflows/govulncheck.yml
  .markdownlint-cli2.jsonc
  CHANGELOG.md
  CONTRIBUTING.md
  Dockerfile
  MAINTAINER.md
  Makefile
  README.md
  RELEASE.md
  docs/README.md
  docs/cli-arguments.md
  docs/clusterrolebinding-metrics.md
  docs/customresourcestate-metrics.md
  docs/design/metrics-store-performance-optimization.md
  docs/developer/guide.md
  docs/networkpolicy-metrics.md
  docs/persistentvolumeclaim-metrics.md
  go.mod
  go.sum
  tests/e2e.sh
  tests/e2e/README.md
Labels: cncf-cla: yes, lgtm, size/XL, approved, triage/accepted

#2222 feat: Add new metric kube_pod_scheduler
  docs/pod-metrics.md
  internal/store/pod.go
  internal/store/pod_test.go
  pkg/app/server_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted

#2233 refactor: Clean up generator.go
  pkg/metric_generator/generator.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, triage/accepted

#2234 feat: Support filtering annotations allowlist by "*"
  docs/cli-arguments.md
  internal/store/builder.go
  internal/store/builder_test.go
  pkg/app/server.go
  pkg/builder/builder.go
  pkg/builder/types/interfaces.go
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#2247 docs: Add reproduce example in bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage
