Repository kubernetes/kube-state-metrics, pull requests merged in 2023-07, with the labels that each got.

#2112 build: Reorder CI steps to use go mod cache
  .github/workflows/ci.yml
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage

#2105 chore: Update dependencies
  .github/workflows/ci.yml
  .github/workflows/govulncheck.yml
  Makefile
  go.mod
  go.sum
  internal/store/certificatesigningrequest.go
  internal/store/clusterrole.go
  internal/store/clusterrolebinding.go
  internal/store/endpointslice.go
  internal/store/ingressclass.go
  internal/store/mutatingwebhookconfiguration.go
  internal/store/namespace.go
  internal/store/node.go
  internal/store/persistentvolume.go
  internal/store/storageclass.go
  internal/store/validatingwebhookconfiguration.go
  pkg/app/server_test.go
  pkg/builder/builder_test.go
  pkg/metrics_store/metrics_store.go
  tools/go.mod
  tools/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#2126 chore: Remove myself from maintainers
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage

#2122 fix: Add filtering for Lease metrics
  internal/store/lease.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage

#2114 feat: Add webhooks client config service metrics
  docs/mutatingwebhookconfiguration-metrics.md
  docs/validatingwebhookconfiguration-metrics.md
  internal/store/mutatingwebhookconfiguration.go
  internal/store/mutatingwebhookconfiguration_test.go
  internal/store/validatingwebhookconfiguration.go
  internal/store/validatingwebhookconfiguration_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, kind/feature, triage/accepted

#2074 feat(pvc): support kube_persistentvolumeclaim_deletion_timestamp
  docs/persistentvolumeclaim-metrics.md
  internal/store/persistentvolumeclaim.go
  internal/store/persistentvolumeclaim_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted

#2075 feat(pv): support kube_persistentvolume_deletion_timestamp
  docs/persistentvolume-metrics.md
  internal/store/persistentvolume.go
  internal/store/persistentvolume_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted

#2096 feat: Adds new metric `kube_pod_service_account`
  docs/pod-metrics.md
  internal/store/pod.go
  internal/store/pod_test.go
  pkg/app/server_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted

#2127 chore: Sync security contacts with approvers
  SECURITY_CONTACTS
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage
