Repository kubernetes/kube-state-metrics, pull requests merged in 2024-08, with the labels that each got.

#2464 chore: Avoid naked return
  pkg/watch/watch.go
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-triage

#2465 chore: Replace NewReflector with NewReflectorWithOptions func
  internal/store/builder.go
  tests/lib/lib_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage

#2454 fix: syntax errors in kube-state-metrics.libsonnet
  examples/daemonsetsharding/deployment-no-node-pods-service.yaml
  examples/daemonsetsharding/deployment-no-node-pods.yaml
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted

#2467 fix: e2e test failure
  examples/daemonsetsharding/deployment-unscheduled-pods-fetching-service.yaml
  examples/daemonsetsharding/deployment-unscheduled-pods-fetching.yaml
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
  tests/e2e.sh
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-triage

#2466 chore: Add unused linter
  .golangci.yml
  internal/discovery/discovery_test.go
  internal/store/networkpolicy_test.go
  pkg/metrics_store/metrics_store_test.go
  pkg/util/utils.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage

#2479 docs: Fix outdated RegistryFactory.MetricFamilyGenerators comments
  pkg/customresource/registry_factory.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage

#2469 chore: Bump e2e kind node to 1.30
  tests/e2e.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, triage/accepted

#2470 chore: Memory align structs
  internal/discovery/types.go
  internal/store/builder.go
  internal/store/pod.go
  internal/store/testutils.go
  pkg/customresourcestate/config.go
  pkg/customresourcestate/config_metrics_types.go
  pkg/customresourcestate/registry_factory.go
  pkg/metric_generator/generator.go
  pkg/metrics_store/metrics_store.go
  pkg/metricshandler/metrics_handler.go
  pkg/options/options.go
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted
