Repository kubernetes/kube-state-metrics, pull requests merged in 2024-11, with the labels that each got.

#2540 fix: big memory overflow
  internal/store/horizontalpodautoscaler.go
  internal/store/limitrange.go
  internal/store/node.go
  internal/store/node_test.go
  internal/store/pod.go
  internal/store/resourcequota.go
  internal/store/utils.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-triage

#2510 perf: use concurrent map when storing metrics
  pkg/metrics_store/metrics_store.go
  pkg/metrics_store/metrics_writer.go
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted

#2539 fix: expose empty labels
  internal/store/endpoint.go
  internal/store/endpoint_test.go
  internal/store/endpointslice.go
  internal/store/endpointslice_test.go
  internal/store/pod.go
  internal/store/pod_test.go
  internal/store/serviceaccount.go
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#2545 chore: Improve benchmarks
  .github/workflows/ci.yml
  Makefile
  pkg/app/server_test.go
  tests/compare_benchmarks.sh
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage

#2546 chore: Fix broken CI
  .github/workflows/ci.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage

#2542 feat: Add new metric kube_job_status_suspended
  docs/metrics/workload/job-metrics.md
  internal/store/job.go
  internal/store/job_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage

#2547 fix: Remove redundant factories array since it is not written after
  pkg/app/server.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage

#2548 chore: Bump versions
  Makefile
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage

#2536 fix(custom resource state metrics): correctly convert status condition `Unknown` to a valid value
  docs/metrics/extend/customresourcestate-metrics.md
  pkg/customresourcestate/registry_factory.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, triage/accepted

#2538 chore: Cut v2.14.0
  CHANGELOG.md
  README.md
  data.yaml
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/daemonsetsharding/cluster-role-binding.yaml
  examples/daemonsetsharding/cluster-role.yaml
  examples/daemonsetsharding/daemonset-service.yaml
  examples/daemonsetsharding/daemonset.yaml
  examples/daemonsetsharding/deployment-service.yaml
  examples/daemonsetsharding/deployment.yaml
  examples/daemonsetsharding/service-account.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage

#2552 chore: Merge Release 2.14 back to main
  CHANGELOG.md
  README.md
  data.yaml
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/daemonsetsharding/cluster-role-binding.yaml
  examples/daemonsetsharding/cluster-role.yaml
  examples/daemonsetsharding/daemonset-service.yaml
  examples/daemonsetsharding/daemonset.yaml
  examples/daemonsetsharding/deployment-service.yaml
  examples/daemonsetsharding/deployment.yaml
  examples/daemonsetsharding/service-account.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage

#2376 feat: Add timezone to kube_cronjob_info / Make kube_cronjob_next_schedule_time timezone-aware
  docs/metrics/workload/cronjob-metrics.md
  internal/store/cronjob.go
  internal/store/cronjob_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#2415 feat: Promote kube_statefulset_ordinals_start from ALPHA -> STABLE
  docs/metrics/workload/statefulset-metrics.md
  internal/store/statefulset.go
  internal/store/statefulset_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, triage/accepted

#2528 docs: Add best practices for metrics
  docs/design/metrics-best-practices.md
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted
