Repository kubernetes/kube-state-metrics, pull requests merged in 2024-07, with the labels that each got.

#2442 fix: add `readyz` endpoint
  README.md
  README.md.tpl
  examples/autosharding/statefulset.yaml
  examples/daemonsetsharding/daemonset.yaml
  examples/daemonsetsharding/deployment-no-node-pods.yaml
  examples/daemonsetsharding/deployment.yaml
  examples/standard/deployment.yaml
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
  pkg/app/server.go
  pkg/util/utils.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-triage

#2447 perf: Add automatic detection of memory limits
  docs/developer/cli-arguments.md
  go.mod
  go.sum
  pkg/app/server.go
  pkg/options/options.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage

#2419 chore: Prep release v2.13.0
  CHANGELOG.md
  Makefile
  README.md
  data.yaml
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/daemonsetsharding/cluster-role-binding.yaml
  examples/daemonsetsharding/cluster-role.yaml
  examples/daemonsetsharding/daemonset-service.yaml
  examples/daemonsetsharding/daemonset.yaml
  examples/daemonsetsharding/deployment-no-node-pods.yaml
  examples/daemonsetsharding/deployment-service.yaml
  examples/daemonsetsharding/deployment.yaml
  examples/daemonsetsharding/service-account.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-rebase, needs-triage

#2450 chore: Merge release branch back to main
  CHANGELOG.md
  Makefile
  README.md
  data.yaml
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/daemonsetsharding/cluster-role-binding.yaml
  examples/daemonsetsharding/cluster-role.yaml
  examples/daemonsetsharding/daemonset-service.yaml
  examples/daemonsetsharding/daemonset.yaml
  examples/daemonsetsharding/deployment-no-node-pods.yaml
  examples/daemonsetsharding/deployment-service.yaml
  examples/daemonsetsharding/deployment.yaml
  examples/daemonsetsharding/service-account.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-triage

#2451 ci: missing line break escape on sbom workflow
  .github/workflows/sbom.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage

#2388 fix: use --track-unscheduled-pods to select unscheduled pods in Daemonset sharding
  README.md
  README.md.tpl
  docs/developer/cli-arguments.md
  examples/daemonsetsharding/deployment-no-node-pods-service.yaml
  examples/daemonsetsharding/deployment-no-node-pods.yaml
  jsonnet/kube-state-metrics/kube-state-metrics.libsonnet
  pkg/app/server.go
  pkg/options/options.go
  pkg/options/types.go
  pkg/options/types_test.go
  tests/e2e.sh
  tests/e2e/testdata/pods.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#2456 fix(Dockerfile): Install tools so VERSION gets set
  Dockerfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage
