Repository kubernetes/kube-state-metrics, pull requests merged in 2024-04, with the labels that each got.

#2352 chore: Bump prometheus/common library
  go.mod
  go.sum
  pkg/app/server.go
  pkg/metrics_store/metrics_writer_test.go
  pkg/metricshandler/metrics_handler.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage

#2335 chore: Cut v2.12.0
  CHANGELOG.md
  README.md
  VERSION
  data.yaml
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/daemonsetsharding/cluster-role-binding.yaml
  examples/daemonsetsharding/cluster-role.yaml
  examples/daemonsetsharding/daemonset-service.yaml
  examples/daemonsetsharding/daemonset.yaml
  examples/daemonsetsharding/deployment-no-node-pods.yaml
  examples/daemonsetsharding/deployment-service.yaml
  examples/daemonsetsharding/deployment.yaml
  examples/daemonsetsharding/service-account.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-rebase, triage/accepted

#2361 chore: Replace VERSION file with data.yaml
  Makefile
  RELEASE.md
  VERSION
  data.yaml
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-triage

#2363 chore: use string verb to format logging messages in tests
  tests/e2e/main_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage

#2362 chore: Build with go 1.22
  .github/workflows/ci.yml
  .github/workflows/govulncheck.yml
  .golangci.yml
  Dockerfile
  Makefile
  docs/metrics/workload/pod-metrics.md
  internal/store/clusterrole.go
  internal/store/configmap.go
  internal/store/endpoint.go
  internal/store/job.go
  internal/store/mutatingwebhookconfiguration.go
  internal/store/role.go
  internal/store/secret.go
  internal/store/validatingwebhookconfiguration.go
  main.go
  pkg/app/server.go
  pkg/app/server_test.go
  pkg/metrics_store/metrics_store_test.go
  pkg/metrics_store/metrics_writer_test.go
  pkg/options/options.go
  tests/e2e/discovery_test.go
  tests/e2e/hot-reload-kubeconfig_test.go
  tests/e2e/hot-reload_test.go
  tests/e2e/main_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted

#2370 feat: add kube_persistentvolume_volume_mode metric
  docs/metrics/storage/persistentvolume-metrics.md
  internal/store/persistentvolume.go
  internal/store/persistentvolume_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, triage/accepted
