Repository kubernetes/kube-state-metrics, pull requests merged in 2024-12, with the labels that each got.

#2567 fix: Fix CR cache for GVK all specified case
  internal/discovery/discovery.go
  internal/discovery/discovery_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage

#2556 chore: Bump versions
  Dockerfile
  Makefile
  cloudbuild.yaml
  tests/e2e.sh
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-triage

#2573 style: fix warning during docker build
  Dockerfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, triage/accepted

#2577 docs: update links to openmetrics to reference the v1.0.0 release
  docs/metrics/extend/customresourcestate-metrics.md
  pkg/customresourcestate/config_metrics_types.go
  pkg/metric/metric.go
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-triage
