Repository kubernetes/kube-state-metrics, pull requests merged in 2024-10, with the labels that each got.

#2502 fix: de-duplication of custom resource metrics
  internal/store/builder.go
  internal/store/builder_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted

#2478 fix(discovery): configure sharding every time MetricsHandler.Run runs
  internal/discovery/discovery.go
  pkg/app/server.go
  pkg/metricshandler/metrics_handler.go
  tests/e2e/discovery_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#2526 fix: update govulncheck's go version to 1.23
  .github/workflows/govulncheck.yml
  Dockerfile
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage

#2527 chore: Remove deprecated endpoint address metric
  docs/metrics/service/endpoint-metrics.md
  internal/store/endpoint.go
  internal/store/endpoint_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage

#2503 feat: Move endpoint ports into address metric
  docs/metrics/service/endpoint-metrics.md
  internal/store/endpoint.go
  internal/store/endpoint_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#2535 fix: panic in `util.GVRFromType` for core objects
  pkg/util/utils.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage
