Repository kubernetes/kube-state-metrics, pull requests merged in 2024-09, with the labels that each got.

#2498 docs: fix unformatted code blocks in README
  README.md
  README.md.tpl
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-triage

#2485 fix: set kube_job_status_failed metric even when there are no job.Status.Conditions present
  internal/store/job.go
  internal/store/job_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted

#2508 chore: Migrate to slog for exporter-toolkit
  go.mod
  go.sum
  pkg/app/server.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage

#2492 chore: Bump to kubernetes 1.31.0
  README.md
  data.yaml
  docs/metrics/cluster/node-metrics.md
  go.mod
  go.sum
  internal/store/node.go
  internal/store/node_test.go
  tests/e2e.sh
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#2509 chore: Fix the security issue about sirupsen/logrus
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-triage
