Repository kubernetes/kube-state-metrics, pull requests merged in 2024-03, with the labels that each got.

#2317 chore: Cut v2.11.0
  CHANGELOG.md
  Makefile
  README.md
  VERSION
  docs/lease-metrics.md
  docs/secret-metrics.md
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/daemonsetsharding/cluster-role-binding.yaml
  examples/daemonsetsharding/cluster-role.yaml
  examples/daemonsetsharding/daemonset-service.yaml
  examples/daemonsetsharding/daemonset.yaml
  examples/daemonsetsharding/deployment-no-node-pods.yaml
  examples/daemonsetsharding/deployment-service.yaml
  examples/daemonsetsharding/deployment.yaml
  examples/daemonsetsharding/service-account.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
  go.mod
  go.sum
  internal/store/secret.go
  internal/store/secret_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#2334 chore: Sync `release-2.11`
  CHANGELOG.md
  Makefile
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/daemonsetsharding/cluster-role-binding.yaml
  examples/daemonsetsharding/cluster-role.yaml
  examples/daemonsetsharding/daemonset-service.yaml
  examples/daemonsetsharding/daemonset.yaml
  examples/daemonsetsharding/deployment-no-node-pods.yaml
  examples/daemonsetsharding/deployment-service.yaml
  examples/daemonsetsharding/deployment.yaml
  examples/daemonsetsharding/service-account.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted

#2291 feat: add kube_pod_container_status_last_terminated_timestamp metric
  docs/pod-metrics.md
  internal/store/pod.go
  internal/store/pod_test.go
  pkg/app/server_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted

#2052 feat: Allow prefixing wildcard `labelsFromPath`
  docs/customresourcestate-metrics.md
  pkg/customresourcestate/registry_factory.go
  pkg/customresourcestate/registry_factory_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted

#2343 chore: Bump kubernetes 1.29 deps
  .github/dependabot.yml
  README.md
  go.mod
  go.sum
  internal/store/persistentvolumeclaim_test.go
  tests/e2e.sh
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage

#2270 fix: fallback to `gauge` for `protofmt`-based negotiations
  pkg/customresourcestate/config.go
  pkg/customresourcestate/config_metrics_types.go
  pkg/customresourcestate/config_test.go
  pkg/customresourcestate/custom_resource_metrics_test.go
  pkg/customresourcestate/registry_factory.go
  pkg/metric/metric.go
  pkg/metrics_store/metrics_writer.go
  pkg/metrics_store/metrics_writer_test.go
  pkg/metricshandler/metrics_handler.go
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted
