Repository kubernetes/kube-state-metrics, pull requests merged in 2025-09, with the labels that each got.

#2730 fix: Fix logic for plain text fallback format
  pkg/metrics_store/metrics_writer.go
  pkg/metrics_store/metrics_writer_test.go
  pkg/metricshandler/metrics_handler.go
Labels: cncf-cla: yes, lgtm, size/S, approved, triage/accepted

#2757 chore: Prepare v2.17.0
  CHANGELOG.md
  README.md
  data.yaml
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/daemonsetsharding/cluster-role-binding.yaml
  examples/daemonsetsharding/cluster-role.yaml
  examples/daemonsetsharding/daemonset-service.yaml
  examples/daemonsetsharding/daemonset.yaml
  examples/daemonsetsharding/deployment-service.yaml
  examples/daemonsetsharding/deployment-unscheduled-pods-fetching-service.yaml
  examples/daemonsetsharding/deployment-unscheduled-pods-fetching.yaml
  examples/daemonsetsharding/deployment.yaml
  examples/daemonsetsharding/service-account.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted

#2761 chore: Merge v2.17.0 back into main
  CHANGELOG.md
  README.md
  data.yaml
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/daemonsetsharding/cluster-role-binding.yaml
  examples/daemonsetsharding/cluster-role.yaml
  examples/daemonsetsharding/daemonset-service.yaml
  examples/daemonsetsharding/daemonset.yaml
  examples/daemonsetsharding/deployment-service.yaml
  examples/daemonsetsharding/deployment-unscheduled-pods-fetching-service.yaml
  examples/daemonsetsharding/deployment-unscheduled-pods-fetching.yaml
  examples/daemonsetsharding/deployment.yaml
  examples/daemonsetsharding/service-account.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted

#2749 feat: Promote many metrics from ALPHA -> STABLE
  docs/metrics/workload/cronjob-metrics.md
  docs/metrics/workload/horizontalpodautoscaler-metrics.md
  docs/metrics/workload/pod-metrics.md
  internal/store/cronjob.go
  internal/store/horizontalpodautoscaler.go
  internal/store/pod.go
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-triage

#2771 feat: Add kube_job_status_ready metric
  docs/metrics/workload/job-metrics.md
  internal/store/job.go
  internal/store/job_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage
