Repository kubernetes/kube-state-metrics, pull requests merged in 2025-06, with the labels that each got.

#2677 chore: Bump kind
  tests/e2e.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage

#2687 fix: Fix typo in Makefile
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage

#2672 fix: Clean up CR reflectors after parent CRD deletion
  internal/discovery/discovery.go
  internal/discovery/types.go
  internal/store/builder.go
  pkg/app/server.go
Labels: cncf-cla: yes, lgtm, size/S, approved, triage/accepted

#2689 chore: Bump to k8s 1.32.6
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage
