Repository kubernetes/kube-state-metrics, pull requests merged in 2025-08, with the labels that each got.

#2705 fix: Config file overrides apply to some fields but not other
  docs/developer/cli-arguments.md
  pkg/app/server.go
  pkg/app/server_test.go
  pkg/options/options.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test, triage/accepted

#2720 chore: Build with k8s 1.33
  .golangci.yml
  README.md
  data.yaml
  go.mod
  go.sum
  tests/e2e.sh
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-triage

#2714 fix: Fixed the format of Markdown files
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .markdownlint-cli2.jsonc
  .openvex/templates/README.md
  CHANGELOG.md
  README.md
  README.md.tpl
  RELEASE.md
  docs/README.md
  docs/design/metrics-store-performance-optimization.md
  docs/metrics/extend/customresourcestate-metrics.md
  docs/metrics/service/ingress-metrics.md
  docs/metrics/storage/persistentvolume-metrics.md
  tests/e2e/README.md
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-triage

#2675 feat: Add HorizontalPodAutoscaler created and deletionTimestamp info into metrics
  docs/metrics/workload/horizontalpodautoscaler-metrics.md
  internal/store/horizontalpodautoscaler.go
  internal/store/horizontalpodautoscaler_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted

#2678 feat: introduce deletion timestamp metric for daemonset, statefulset, deployment, service and pdb
  docs/metrics/policy/poddisruptionbudget-metrics.md
  docs/metrics/service/service-metrics.md
  docs/metrics/workload/daemonset-metrics.md
  docs/metrics/workload/deployment-metrics.md
  docs/metrics/workload/statefulset-metrics.md
  internal/store/daemonset.go
  internal/store/daemonset_test.go
  internal/store/deployment.go
  internal/store/deployment_test.go
  internal/store/poddisruptionbudget.go
  internal/store/poddisruptionbudget_test.go
  internal/store/service.go
  internal/store/service_test.go
  internal/store/statefulset.go
  internal/store/statefulset_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, triage/accepted
